### ISSUE TITLE
TemporaryBackendException while using janusgraph java api and hbase

### ISSUE THREAD

**Issue by SummerLitchy** [JanusGraph/janusgraph#1156] opened 2018-07-08 03:44 UTC
**I am using the same code in Java API and Gremlin shell, why the Gremlin shell works but the Java API gets an error?**

Details:
I am using JanusGraph Java API, with HBase as storage backend

One thing I have to mention is that I can successfully run the same commands in JanusGraph shell, `gremlin.sh`

The log before the error is below, which happens during the opening of the graph instance, `JanusGraphFactory.open(jg.properties)`

    07:20:46.169 [main-SendThread(cdh-master1:2181)] DEBUG org.apache.zookeeper.ClientCnxn - 
    Reading reply sessionid:0x263f89ba9d56ce2, 
    packet:: clientPath:null serverPath:null finished:false header:: 3,8  replyHeader:: 3,55834924519,0  
    request:: '/hbase,F  response:: v{'replication,'meta-region-server,'rs,'splitWAL,'backup-masters,
    'table-lock,'flush-table-proc,'region-in-transition,'online-snapshot,'master,'running,'recovering-regions,'draining,'namespace,'hbaseid,'table} 
    07:20:46.182 [main] WARN  o.j.d.hbase.HBaseStoreManager - Unexpected exception during getDeployment()

and the error is 
 
    java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:364) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:403) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1377) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:80) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]

I have no idea with this `TemporaryBackendException`, has anyone met this before?

part of the janusgraph config is 

    gremlin.graph=org.janusgraph.core.JanusGraphFactory
    cluster.max-partitions=64
    storage.backend=hbase
    storage.batch-loading=true
    storage.hostname=cdh-master1,cdh-master2,cdh-master3

where `cdh-master1,2,3` are zookeeper quorum, version JanusGraph 2.0, HBase 1.2

The full stack trace is 

    at my.graph.Graph.<clinit>(Graph.java:7) [rsrc:./:na]
	at my.graph.App.main(App.java:24) [rsrc:./:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58) [janus.jar:na]
    Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:739) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getLocalKeyPartition(HBaseStoreManager.java:524) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:361) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
	... 12 common frames omitted
    Caused by: org.apache.hadoop.hbase.DoNotRetryIOException: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.translateException(RpcRetryingCaller.java:229) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:202) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:320) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:295) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:160) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:155) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:821) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:303) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:111) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:716) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
	... 14 common frames omitted
    Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.hbase.zookeeper.MetaTableLocator
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:596) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:580) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.zookeeper.MetaTableLocator.blockUntilAvailable(MetaTableLocator.java:559) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getMetaRegionLocation(ZooKeeperRegistry.java:61) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateMeta(ConnectionManager.java:1185) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1152) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.getRegionLocations(RpcRetryingCallerWithReadReplicas.java:300) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:151) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:59) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200) ~[jar:rsrc:hbase-client-1.1.2.jar!/:na]
	... 24 common frames omitted

part of my `pom.mxl` including the dependency information is

    <dependency>
   		<groupId>org.janusgraph</groupId>
   		<artifactId>janusgraph-core</artifactId>
   		<version>0.2.0</version>
	</dependency>
	<dependency>
   		<groupId>org.janusgraph</groupId>
   		<artifactId>janusgraph-hbase</artifactId>
   		<version>0.2.0</version>
	</dependency>
	<dependency>
   		<groupId>org.apache.hbase</groupId>
   		<artifactId>hbase-client</artifactId>
   		<version>1.1.2</version>
	</dependency>

**Comment by pluradj** [comment] 2018-07-13 21:50
I'd suggest trying the dependencies as listed in the HBase example
https://github.com/JanusGraph/janusgraph/blob/v0.2.0/janusgraph-examples/example-hbase/pom.xml#L22-L33

**Comment by SummerLitchy** [comment] 2018-07-14 05:52
I am using following this example, I read some other materials and it seems to be the version conflict of Guava.
What I am still curious is, is gremlin shell working based on Java API? Why they use different Guava version, since we do not specify the Guava in our `pom.xml`?

**Comment by pluradj** [comment] 2018-07-14 15:55
Yes, clearly this is a Guava version conflict issue. The HBase example I pointed you to before does not run into a Guava version error because of its specific dependencies listed and the order of those dependencies.

```
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-hbase</artifactId>
            <version>${project.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-shaded-client</artifactId>
            <version>${hbase100.version}</version>
            <scope>runtime</scope>
        </dependency>
```

Note the usage of `hbase-shaded-client` ( fixed with #512 ) rather than `hbase-client` in your `pom.xml` which has a shaded version of Guava for use with HBase. Shading renames the package names of some of the dependencies, and this allows you to have different versions of Guava on the classpath without causing conflicts.

The Gremlin Console uses the `hbase-shaded-client` also and you can find that jar in the `lib` directory of the distribution.

**Closed** 2018-07-14 15:56 UTC
Labels: hbase, question

**Comment by msalihkarakasli** [comment] 2018-07-16 11:05
Dear all, I faced similar problem but it is not related to StopWatch class.
I have been trying to solve this issue for 2 days. I used below docker-compose file to run HBASE and it works well, i can connect it on shell and create table for test.
https://github.com/big-data-europe/docker-hbase

`14:00:17.016 [main] WARN  o.j.d.hbase.HBaseStoreManager - Unexpected exception during getDeployment()
java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:364) ~[janusgraph-hbase-0.2.0.jar:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:403) ~[janusgraph-hbase-0.2.0.jar:na]
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1377) [janusgraph-core-0.2.0.jar:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164) [janusgraph-core-0.2.0.jar:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133) [janusgraph-core-0.2.0.jar:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:80) [janusgraph-core-0.2.0.jar:na]
	at pluradj.janusgraph.example.JavaExample.main(JavaExample.java:20) [classes/:na]
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:739) ~[janusgraph-hbase-0.2.0.jar:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getLocalKeyPartition(HBaseStoreManager.java:524) ~[janusgraph-hbase-0.2.0.jar:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:361) ~[janusgraph-hbase-0.2.0.jar:na]
	... 6 common frames omitted
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Mon Jul 16 14:00:16 EET 2018, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=60186: row 'graph3,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase-region,16020,1531767447643, seqNum=0

	at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.throwEnrichedException(RpcRetryingCallerWithReadReplicas.java:276) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:210) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:60) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:327) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ClientScanner.nextScanner(ClientScanner.java:302) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ClientScanner.initializeScannerInConstruction(ClientScanner.java:167) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ClientScanner.<init>(ClientScanner.java:162) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.HTable.getScanner(HTable.java:797) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.MetaTableAccessor.fullScan(MetaTableAccessor.java:602) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:366) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:406) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:111) ~[janusgraph-hbase-0.2.0.jar:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:716) ~[janusgraph-hbase-0.2.0.jar:na]
	... 8 common frames omitted
Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=60186: row 'graph3,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=hbase-region,16020,1531767447643, seqNum=0
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:169) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
Caused by: java.net.UnknownHostException: hbase-region
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.<init>(AbstractRpcClient.java:315) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.createBlockingRpcChannel(AbstractRpcClient.java:267) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getClient(ConnectionManager.java:1639) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ScannerCallable.prepare(ScannerCallable.java:163) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.prepare(ScannerCallableWithReplicas.java:376) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:134) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
	... 4 common frames omitted
14:00:17.032 [main] DEBUG o.j.d.hbase.HBaseStoreManager - Substituted default CF name "system_properties" with short form "s" to reduce HBase KeyValue size`

Pom XML of my project is like that;
`        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-core</artifactId>
            <version>0.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-hbase</artifactId>
            <version>0.2.0</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-shaded-client</artifactId>
            <version>1.2.6</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-solr</artifactId>
            <version>0.2.0</version>
            <scope>runtime</scope>
        </dependency>`

Configuration file is like that;
`gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=hbase
storage.hostname=10.122.216.235
storage.hbase.ext.hbase.zookeeper.property.clientPort=2181
storage.hbase.table=graph3
`

And this is one line code to try connect HBASE;

`JanusGraph graph = JanusGraphFactory.open("conf/janusgraph.properties");`

What is the missing point?

**Comment by danxinzhujian** [comment] 2019-03-30 05:58
I'm facing the question, too.

**Comment by danxinzhujian** [comment] 2019-03-30 05:58
13:58:29.330 [main] DEBUG o.a.h.h.client.RpcRetryingCallerImpl - Call exception, tries=12, retries=16, started=107476 ms ago, cancelled=false, msg=can not resolve graph,16201,1553925181159, details=row 'janusgraph' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=graph,16201,1553925181159, seqNum=-1, see https://s.apache.org/timeout, exception=java.net.UnknownHostException: can not resolve graph,16201,1553925181159
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.createAddr(AbstractRpcClient.java:430)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.createBlockingRpcChannel(AbstractRpcClient.java:507)
	at org.apache.hadoop.hbase.client.ConnectionImplementation.lambda$getClient$2(ConnectionImplementation.java:1214)
	at org.apache.hadoop.hbase.util.CollectionUtils.computeIfAbsentEx(CollectionUtils.java:61)
	at org.apache.hadoop.hbase.client.ConnectionImplementation.getClient(ConnectionImplementation.java:1212)
	at org.apache.hadoop.hbase.client.ClientServiceCallable.setStubByServiceName(ClientServiceCallable.java:44)
	at org.apache.hadoop.hbase.client.RegionServerCallable.prepare(RegionServerCallable.java:229)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:105)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:386)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:360)
	at org.apache.hadoop.hbase.MetaTableAccessor.getTableState(MetaTableAccessor.java:1078)
	at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:403)
	at org.apache.hadoop.hbase.client.HBaseAdmin$6.rpcCall(HBaseAdmin.java:450)
	at org.apache.hadoop.hbase.client.HBaseAdmin$6.rpcCall(HBaseAdmin.java:447)
	at org.apache.hadoop.hbase.client.RpcRetryingCallable.call(RpcRetryingCallable.java:58)
	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3089)
	at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3081)
	at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:447)
	at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:111)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:724)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getLocalKeyPartition(HBaseStoreManager.java:536)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:375)
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:417)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1256)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:160)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:131)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:78)
	at SecondTest.main(SecondTest.java:19)

**Comment by danxinzhujian** [comment] 2019-03-30 05:59
Is someone can help me?

**Comment by Litchilitchy** [comment] 2019-04-01 08:06
@danxinzhujian the link above https://github.com/JanusGraph/janusgraph/blob/v0.2.0/janusgraph-examples/example-hbase/pom.xml#L22-L33 actually solve my problem. Use `hbase-shaded-client` and there is no conflict anymore.
