### ISSUE TITLE
While committing graph getting exception, caused by: org.janusgraph.diskstorage.locking.consistentkey.ExpiredLockException: Expired lock on KeyColumn 

### ISSUE THREAD

**Issue by sumandas0** [JanusGraph/janusgraph#3363] opened 2022-12-05 07:38 UTC
I have made many mutations on the graph, mostly soft deleting the vertices(Using it inside Apache Atlas). Then I tried to commit the graph and faced this exception,
```
org.janusgraph.diskstorage.locking.consistentkey.ExpiredLockException: Expired lock on KeyColumn [k=0x0x011689A034623463616665322D613739612D343666332D386531632D6436643165323562383664B1, c=0x0x00]: lock timestamp 2022-12-02T07:48:53.522Z Micros is older than storage.lock.expiry-time=PT5M
    at org.janusgraph.diskstorage.locking.consistentkey.ConsistentKeyLocker.checkSingleLock(ConsistentKeyLocker.java:472)
    at org.janusgraph.diskstorage.locking.consistentkey.ConsistentKeyLocker.checkSingleLock(ConsistentKeyLocker.java:131)
    at org.janusgraph.diskstorage.locking.AbstractLocker.checkLocks(AbstractLocker.java:348)
    at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkAllLocks(ExpectedValueCheckingTransaction.java:178)
    at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.prepareForMutations(ExpectedValueCheckingTransaction.java:157)
    at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStoreManager.mutateMany(ExpectedValueCheckingStoreManager.java:77)
    at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:99)
    at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:96)
    at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:66)
    at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:52)
    at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.persist(CacheTransaction.java:96)
    at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.flushInternal(CacheTransaction.java:147)
    at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.commit(CacheTransaction.java:210)
    at org.janusgraph.diskstorage.BackendTransaction.commitStorage(BackendTransaction.java:136)
    at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:790)
    at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1521)
    at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.doCommit(JanusGraphBlueprintsGraph.java:322)
    at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:104)
    at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.commit(JanusGraphBlueprintsGraph.java:300)
    at org.apache.atlas.repository.graphdb.janus.AtlasJanusGraph.commit(AtlasJanusGraph.java:265)
    at org.apache.atlas.GraphTransactionInterceptor.doCommit(GraphTransactionInterceptor.java:186)
    at org.apache.atlas.GraphTransactionInterceptor.doCommitOrRollback(GraphTransactionInterceptor.java:181)
    at org.apache.atlas.GraphTransactionInterceptor.invoke(GraphTransactionInterceptor.java:120)
```

Janusgraph Version : 0.6.0(Embedded JanusGraph)
Backend Storage: Cassandra
I want to know why this exception occur in general.

**Comment by FlorianHockmann** [comment] 2022-12-05 11:23
Closing this as it's not a bug, but a usage question. You have also already posted this question [here as discussion](https://github.com/JanusGraph/janusgraph/discussions/3359) and you also got responses there.
Please proceed there first to find out what the problem is exactly and only if the discussion leads to the conclusion that there is a bug in JanusGraph, create an issue in GitHub.
We are only using GitHub issues for concrete bug reports or feature requests. Everything else should be handled outside of issues in one of the community channels, like GitHub Discussions.

**Closed by FlorianHockmann** 2022-12-05 11:23 UTC
Labels: kind/bug/possible
