### ISSUE TITLE
Performance issue on vertex cache with Guava implementation

### ISSUE THREAD

**Issue by ministat** [JanusGraph/janusgraph#3185] opened 2022-08-27 03:22 UTC
JanusGraph's GuavaVertexCache will cause memory leak in 100% read and heavy read scenario, especially used in OLAP cases. The Guava cache should be replaced by Caffiene cache to fix this issue according to Guava's community feedback.
See https://github.com/google/guava/issues/2408 and https://github.com/google/guava/issues/2063.

In my local JanusGraph, after I replaced Guava cache with Caffeine cache, the OLAP case, for example, g.V().count() takes 18 minutes to finish the scan of a graph with 500 million vertex and 6 billion edges. Before this fix, it takes 45 minutes. So, the fix gets ~3X benefit.

For confirmed bugs, please report:

- Version: All versions before 0.6.2, including 0.6.2
- Storage Backend: hbase, inmemory, cql
- Mixed Index Backend: 
- Link to discussed bug: https://github.com/google/guava/issues/2408, https://github.com/google/guava/issues/2063
- Expected Behavior: vertex cache should not be the top 1 memory leak suspect
- Current Behavior: Guava vertex cache caused leak suspects from JVM heap dump
- Steps to Reproduce: develop a java app which initialize GuavaVertexCache with 30 element size, and launch multiple threads to call get() in a loop. The loop should be, for example, 1,000,000. Use 

### Stack Trace (if you have one)

```
paste stack trace here
```

**Comment by li-boxuan** [comment] 2022-08-27 23:53
Thanks for reporting @ministat! Seems a duplicate of https://github.com/JanusGraph/janusgraph/issues/871 (which was created by the author of Guava, interesting!). Usually, we close newer issues if they are duplicates, but your discovery and experiments are very valuable so I'd like to keep both issues open. Would you like to contribute your implementation back to the community by submitting a PR? That would be very helpful!

**Comment by ministat** [comment] 2022-08-28 07:35
Thanks for your quick response.

I don't know how to pass CLA check, and created duplicate PR by mistake.

What I have found is replacing Guava cache with Caffeine cache gives big benefit. In my OLAP test, I got 3X improvement.


发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: Boxuan Li ***@***.***>
发送时间: 2022年8月28日 7:54
收件人: JanusGraph/janusgraph ***@***.***>
抄送: Hongjiang Zhang ***@***.***>; Mention ***@***.***>
主题: Re: [JanusGraph/janusgraph] Performance issue on vertex cache with Guava implementation (Issue #3185)


Thanks for reporting @ministat<https://github.com/ministat>! Seems a duplicate of #871<https://github.com/JanusGraph/janusgraph/issues/871> (which was created by the author of Guava, interesting!). Usually, we close newer issues if they are duplicates, but your discovery and experiments are very valuable so I'd like to keep both issues open. Would you like to contribute your implementation back to the community by submitting a PR? That would be very helpful!

―

**Comment by porunov** [comment] 2022-08-29 12:19
Identified 8 Guava caches in JanusGraph. Posted them here: https://github.com/JanusGraph/janusgraph/issues/871#issuecomment-1230207577

**Comment by porunov** [comment] 2022-08-31 21:53
Fixed in #3188 
The continuation of work to replace other 7 Guava caches will be tracked in the next issue: #871

**Closed by porunov** 2022-08-31 21:53 UTC
Labels: kind/performance, area/core
