### ISSUE TITLE
Add OLAP traversal support for embeddedcassandra

### ISSUE THREAD

**Issue by geofurb** [JanusGraph/janusgraph#1640] opened 2019-06-25 11:10 UTC
Attempting OLAP traversals with embeddedcassandra as a storage backend results in an error connecting to port 9160, suggesting this is a Thrift issue. Spark OLAP on embeddedcassandra could be beautifully fast; can we get this?

Verified that hdfs is set up correctly and detected by Gremlin; this is a backend issue.

**Comment by porunov** [comment] 2019-06-25 11:51
Duplicate issue: #985 

@geofurb this feature is implemented in #1436 for `0.4.0` version of JanusGraph. The version `0.4.0` isn't released yet but it is expected to be released soon (maybe in several weeks).

Feel free to reopen this feature request issue if I missed something.

**Comment by geofurb** [comment] 2019-06-25 11:54
@porunov #1436 seems to add OLAP support for the cql driver, not the embeddedcassandra driver.

**Comment by porunov** [comment] 2019-06-25 12:26
@geofurb I've never used cassandra in embedded mode. Maybe @FlorianHockmann could comment on this.

**Comment by FlorianHockmann** [comment] 2019-06-25 12:36
Did you enable Thrift in Cassandra? Newer versions have it disabled by default so you have to enable it implicitly.
In general, I would advise against starting a new project with Thrift as support for Thrift will be dropped completely in Cassandra 4 and we will also deprecate it soon in JanusGraph and probably remove it completely in version 0.5.0.
You should instead use CQL which will also support OLAP starting with version 0.4.0 as @porunov already mentioned.

I'm closing this as it's most likely a usage question and not a bug report or feature request and we don't use GitHub issues for that.

**Closed by FlorianHockmann** 2019-06-25 12:36 UTC
