### ISSUE TITLE
Mixed index not used with "or-step"

### ISSUE THREAD

**Issue by severin83** [JanusGraph/janusgraph#701] opened 2017-11-07 14:47 UTC
A query like the following does not make use of the mixed index:
`g.V().or(has('title', textContains('Trump')), has('name', textContains('Trump')))`

In that example, I try to look up a search word in two different fields. I currently can't figure out how to correctly construct that query. A possible workaround would be to make a direct index query.

**Comment by pluradj** [comment] 2017-11-07 14:57
duplicate of #163

**Closed by pluradj** 2017-11-07 14:57 UTC
