### ISSUE TITLE
Please support cypher for gremlin

### ISSUE THREAD

**Issue by bionicles** [JanusGraph/janusgraph#1924] opened 2020-01-09 04:20 UTC
For discussion on internal implementation details of JanusGraph or proposing a [major new feature or subproject](https://docs.janusgraph.org/development/#development-decisions) use the [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev).

**Describe the feature:**
If JanusGraph added this plugin https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-server-plugin it may be possible to support cypher query language relatively easily. If the storage were serverless (like a managed cassandra service) and the janusgraph were containerized and run on serverless container service (like fargate or cloud run) then we could have 100% serverless autoscaling graphs with both cypher and gremlin. If this were infrastructure as code ready with ex: terraform or pulumi or cdk or cfn, the whole stack could be launched with a few termina l commands. And you'd pay nothing if you weren't using it, because it'd be serverless. That sounds like a major win, but i'm not familiar with the codebase... can you please help me add cypher and infrastructure as code?

**Describe a specific use case for the feature:**
startups or prototypes can copy a terraform template and with a couple commands launch a serverless graph with cypher and gremlin

**Comment by FlorianHockmann** [comment] 2020-01-09 08:44
You can simply add this plugin on your own so I don't see why JanusGraph should preinstall this for all users if only some of them are interested in Cypher. We could maybe add a short section to the docs that describe this.

**Comment by bionicles** [comment] 2020-01-09 15:20
I would definitely be down to read and use those docs and I could make the infrastructure as code part. My concern is simply I’m not sure how to install the plugin in the dockerfile

**Comment by FlorianHockmann** [comment] 2020-01-10 12:53
How a dependency can be installed in general is explained [in the TinkerPop docs for the Gremlin Server](http://tinkerpop.apache.org/docs/current/reference/#_configuring_2) which JanusGraph just extends.
As the docs mention, this commands just grabs the JAR and puts it into the `ext` directory. So, you can also do that manually in your Dockerfile instead. But I see that you already created JanusGraph/janusgraph-docker#49 to document this for our Docker image.

**Comment by FlorianHockmann** [comment] 2021-01-20 11:40
Closing this as it's a duplicate of #161.

**Closed by FlorianHockmann** 2021-01-20 11:40 UTC
