### ISSUE TITLE
GremlinServerError: 499: The traversal source [g] for alias [g] is not configured on the server

### ISSUE THREAD

**Issue by WolfgangFahl** [JanusGraph/janusgraph#2868] opened 2021-11-24 07:25 UTC
This is a reminder that #1826 needs to be reopened

**Comment by FlorianHockmann** [comment] 2021-11-25 12:53
@WolfgangFahl I don't see why that issue should be reopened. That error message usually just means that JanusGraph could not instantiate the graph at startup which can simply mean that it could not reach its storage backend. This can be caused by a wide range of reasons and there is no single bug that needs to be solved from all I can see.
The issue in #1826 was the one that the original creator had and it was apparently resolved as they have closed the issue themselves.

There were some other people who described other problems which just also lead to this error message. But I don't think that it helps to discuss everything that somehow leads to this error message in #1826 as we are probably talking about completely different problems then and this just leads to confusion.

If you have another issue where this error message occurs, then please create a new issue where you describe your specific problem. If you are not sure however whether it's actually a bug or not, then please ask instead on our janusgraph-users mailing list as we're only using GitHub issues for bug reports and feature requests. Then we can first try to find out what the problem exactly is and if it is indeed a bug in JanusGraph, then you can still create a bug report here with all the necessary information.
So I'm closing this issue, too.

**Closed by FlorianHockmann** 2021-11-25 12:53 UTC
Labels: kind/bug/possible

**Comment by WolfgangFahl** [comment] 2021-11-25 13:25
I think the software and it's documentation has a problem that should be fixed since so many users do not know what to do when they get this error message. I personally never tried Janusgraph again because of this issue and this outcome is not what a software delivery is about. Users should be able to use a software and not get stuck with a problem like this.

**Comment by FlorianHockmann** [comment] 2021-11-25 15:04
What you have to do as a first step to find the underlying problem is check the JanusGraph Server logs during startup. JanusGraph Server executes a groovy script at startup which creates a graph instance and then binds a graph traversal source `g` to this graph. All traversals are then executed on this graph traversal source. If this Groovy script however failed to execute, then there is no `g` configured on the server which leads to this error message.
So, inspecting the logs that JanusGraph Server produced at startup usually shows what the underlying problem is, like it couldn't reach the configured storage backend.

I understand that this error message can be confusing. We could maybe add the hint to check the logs from the startup of JanusGraph Server to this error message to make it more clear to users how they can debug the underlying problem.

**Comment by ManfredLange** [comment] 2022-01-15 03:55
I found that this issues is not necessarily caused by JanusGraph not being able to reach its storage backend. In my environment I use Cassandra as a storage backend. I have a containerized dev environment, so both, JanusGraph and Cassandra run in their dedicated containers.

In my environment I was able to resolve this issue by deleting the JanusGraph container (not the image) and the create a new container from the same image. This resolve the issue. This leads me to the hypothesis that the JanusGraph container was in a state that didn't allow to perform as expected.

Next time I observe this, I intend to grab the startup log output as suggested by @FlorianHockmann .

I agree with @WolfgangFahl  that to gain more users it's important to provide information to new users how to resolve certain issues, even if it is just a list of things to try.
