### ISSUE TITLE
Guava dependency

### ISSUE THREAD

**Issue by Amooti** [JanusGraph/janusgraph#622] opened 2017-10-12 12:15 UTC
Are there any plans to either remove or shade JanusGraph's Guava dependency? The dependency is problematic when working with Hadoop/Spark/HBase classpaths. I recently switched from Titan to JanusGraph, where I've had the same issues with Guava.

I'm currently using my own JanusGraph fork with a shaded Guava dependency. I've shaded the dependency in core, and changed the imports in the other projects to use this shaded version.

I would be happy to put in the effort to get these changes back into JanusGraph.

**Comment by pluradj** [comment] 2017-10-12 13:23
This has been done with #512 and will be in the 0.2.0 release.

**Closed by pluradj** 2017-10-12 13:23 UTC
Labels: question

**Comment by Amooti** [comment] 2017-10-12 13:38
Will do some testing tomorrow, but I am having problems just using janusgraph-cassandra in a map-reduce job running on hadoop (I'm not using janusgraph-hbase). Maybe the problems will go away with 0.2.0, was using 0.1.1.

**Comment by pluradj** [comment] 2017-10-12 14:43
Ah, I see. Let's consider this a duplicate of #114 and continue conversation on that issue.
