### ISSUE TITLE
Add support for AWS Keyspaces

### ISSUE THREAD

**Issue by adric-work** [JanusGraph/janusgraph#2370] opened 2021-01-21 07:56 UTC
**Describe the feature:**
Add support for AWS Keyspaces' "DefaultPartitioner"

https://stackoverflow.com/questions/62220244/run-janusgraph-with-aws-keyspace-storage-backend

At the moment it looks like there is only support for 
["RandomPartitioner" and "Murmur3Partitioner"](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java#L217-L235)

**Describe a specific use case for the feature:**
I would like to use AWS's managed Cassandra DB "Keyspaces" as my database for [The Hive 4](https://github.com/TheHive-Project/TheHive/issues/1740).  I was able to connect via cqlsh from my The Hive instance, but was unable to get Janusgraph to connect.

Older issue where people are asking for the same feature in the comments: 
https://github.com/TheHive-Project/TheHive/issues/1286

**Comment by farodin91** [comment] 2021-01-21 08:09
I could think we could easily add an option to force usage one of three support partitioner.

**Comment by li-boxuan** [comment] 2021-01-22 14:55
Seems duplicate of https://github.com/JanusGraph/janusgraph/issues/2291

Not sure but I suspect the DataStax driver we are using does not support AWS's DefaultPartitioner. https://community.datastax.com/questions/2989/trying-to-connect-to-aws-cassandra-with-datastaxsp.html

**Comment by bezalel** [comment] 2021-01-28 04:58
> I could think we could easily add an option to force usage one of three support partitioner.

I hope to use AWS managed Cassandra (Keyspaces) as JanusGraph storage backend too!

is it simple issue to be fixed by adding "com.amazonaws.cassandra.DefaultPartitioner" support on CQLStoreManager.java?
[https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java#L217-L235](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java#L217-L235)

**Comment by li-boxuan** [comment] 2021-01-29 12:13
It would be helpful if someone can confirm that the DataStax driver can be used to connect to AWS managed Cassandra first. Otherwise, there is not much JanusGraph can do at the moment.

**Comment by andreacardaropoli** [comment] 2021-02-08 10:56
> It would be helpful if someone can confirm that the DataStax driver can be used to connect to AWS managed Cassandra first. Otherwise, there is not much JanusGraph can do at the moment.

By the looks of it, it should be possible according to AWS documentation: https://docs.aws.amazon.com/keyspaces/latest/devguide/using_java_driver.html#java_tutorial

**Comment by li-boxuan** [comment] 2021-03-01 16:40
I tested today by building a custom janusgraph version. No luck yet. I encountered the same problems reported at https://forums.aws.amazon.com/thread.jspa?messageID=942152 which seems to be a general problem with using Datastax Driver. Unfortunately, the solution on that thread seems to be switching to other drivers.

**Comment by gvassallo** [comment] 2021-05-28 13:25
Hi, @li-boxuan! I see there has been several commits/PRs mentioning this issue. Do you know if as of now it would be possible to use AWS Keyspaces with janusgraph? I saw the patch you linked in your comment and I was wondering if those code changes were still required or if it would be enough to set up the correct configuration now that more options (e.g. selecting a partitioner) are available

**Comment by porunov** [comment] 2021-05-28 14:07
@gvassallo as far as I understand this PR should also be merged #2618 to support Amazon Keyspace but @li-boxuan can answer this question better.

**Comment by li-boxuan** [comment] 2021-05-31 02:24
#2618 is required to be merged. Likely one more small PR is needed as demonstrated [here](https://github.com/li-boxuan/janusgraph/commit/b5072c7829ec8091121f115ddbee746b11a830b2#diff-3f57afc1c568b35ff9e2cb5c0dd0f1016a3aef8b819029e309431c2af3bb6dffR175-R178), because Amazon keyspace does not support token.

**Comment by gvassallo** [comment] 2021-05-31 13:41
Thank you for your answers and for the work you're doing! Some weeks ago I tried to run one of the latest versions of janusgraph with AWS keyspaces and among the things that were not working, I had an issue when selecting the partitioner via configuration. i.e. if you set a partitioner, e.g. `DefaultPartitioner`, the switch case [here](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java#L233) will still throw an exception. Is it something that needs to be adapted as well?

**Comment by li-boxuan** [comment] 2021-05-31 13:47
@gvassallo Yeah you are right... That adds one more small piece into my place 😉  [This](https://github.com/li-boxuan/janusgraph/commit/b5072c7829ec8091121f115ddbee746b11a830b2#diff-e7acaf1d98c639f210cd458192411d7e42bee5900aed88d7fc90d5909781c3baR219) is needed to make it work. I think when I made the PR https://github.com/JanusGraph/janusgraph/pull/2556 I forgot to make that change.

**Comment by gvassallo** [comment] 2021-05-31 13:49
Yes exactly, good that you have that covered :)

**Closed** 2021-06-12 16:30 UTC
Labels: kind/enhancement, storage/cassandra

**Comment by aziv2010** [comment] 2022-04-05 06:56
@li-boxuan Hi Li. As of today, April 5'th 2022, can Janus be used with AWS Keyspaces? Thanks.

**Comment by nadouani** [comment] 2022-04-05 07:36
Hello, with TheHive 5 we use the latest version on JanusGraph but we didn't try Amazon Keyspaces. If JanusGraph supports it, I don't see any reason not to have TheHive work with it

**Comment by aziv2010** [comment] 2022-04-05 07:50
Thanks Nabil.
This still does not answer my query though. I need someone from Janus to
approve this.

Bye,
  Avi

**Comment by li-boxuan** [comment] 2022-04-05 14:51
@aziv2010 Yes, it's an experimental feature. You are more than welcome to try it and let us know if there is any issue. https://docs.janusgraph.org/storage-backend/cassandra/#deploying-on-amazon-keyspaces-experimental

**Comment by nadouani** [comment] 2022-04-05 16:22
@adric-work you've got the answer :) The PR is in JG 0.6.0 which is used by TheHive 5. Good testing.
