### ISSUE TITLE
Categorize tests by runtime

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#5] opened 2016-12-31 00:37 UTC
The full test suite has a timeout of 21600 sec (6 hours) in the [`pom.xml`](https://github.com/JanusGraph/janusgraph/blob/e9a806276a29052279dabb5d3a7cf06849490a05/pom.xml#L239) which far exceeds [Travis' 50 min timeout](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts).

Experimentally, even following the [`TESTING.md`](https://github.com/JanusGraph/janusgraph/blob/ff59c11ccf01884299047055ea8807bc6e551dec/TESTING.md) category designation and running different groups of tests separately (`OrderedKeyStoreTests`, `UnorderedKeyStoreTests` and default) in separate jobs still times out.

Tests vary dramatically in runtimes: some tests run in < 1 sec, while others take > 300 sec.

One idea is to create categories such as `SmallTests`, `MediumTests`, `LargeTests` (see [blog post](https://testing.googleblog.com/2010/12/test-sizes.html)) or even simply `FastTests` vs. `SlowTests` and use [JUnit `Category` annotations](https://github.com/junit-team/junit4/wiki/Categories) for grouping, and then select subsets of tests for different jobs within a single Travis run, so we can get faster feedback on a change during a code review, even if other parts of the test suite take longer to verify.

**Comment by sjudeng** [comment] 2017-01-13 19:06
The problems I ran into running tests in Travis were sporadic non-timout failures in all but the titan-test module. At the time I guessed it was some kind of test case threading/Travis resource throttling issue, but I didn't dig in. This was consistently a problem with titan-elastic, but sporadically also a problem in titan-berkeleyje, titan-solr and titan-lucene.

Regarding timeout issues, for what it's worth I've found that tests for all modules pass well within 50 minutes, with the exception of titan-cassandra and titan-hbase. This is assuming you're just running the default test suite and not adding in the tinkerpop test suite (e.g. `mvn verify` not `mvn verify -Dtest.skip.tp=false`).

You can see some Travis Titan build history below, where the build matrix executed tests in each module individually.

https://travis-ci.org/ngageoint/titan/builds

Starting from the builds on the bottom you see titan-test always runs without issue, but others fail sporadically but not from timeout. Ultimately I trimmed down to running just titan-test. It would be fantastic if you could get all tests running under Travis, but you might make sure you can identify/squash the non-timeout issue (assuming you can reproduce) before working through timeout issues.

Also I'm not sure if it's still an issue but Travis has a log limit limit that I ran into running tests. I had to update logging config to eliminate debug logging when running tests to get them to run at all under Travis.

https://github.com/ngageoint/titan/commit/00da98b05cd2efd052298228a7bcfba9e559ee2b

**Comment by sjudeng** [comment] 2017-07-18 00:39
Closing this since #74 is resolved.

**Closed by sjudeng** 2017-07-18 00:39 UTC
Labels: testing
