### ISSUE TITLE
Cache related problem in 1.0.0-rc2, coming from CaffeineVertexCache

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#3646] opened 2023-03-07 16:32 UTC
We have recently updated JanusGraph in our internal deployments at G DATA to 1.0.0-rc1 and noticed that this leads to an error for one of our edge labels that was not present before:

```java
java.lang.IllegalArgumentException: Connection constraint does not exist for given Edge Label [EDGE_LABEL], outgoing Vertex Label [OUT_VERTEX] and incoming Vertex Label [IN_VERTEX]
```

The connection constraint however is definitely in the schema and the same traversal works against JanusGraph 0.6.3. We also tried out 1.0.0-rc2 and built directly from `master` to ensure that this hasn't been fixed already.

We unfortunately cannot reproduce this problem easily as it only occurs for just one edge label apparently and even there only for some vertices. But we can at least reproduce it with our productive database for one specific vertex.

So we could use `git bisect` to identify the commit which introduced this problem: c30c7071227de338a63d82336b34f749f2384b22

It looks like the `.executor(Runnable::run)` is responsible for this. Removing just [this one line](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/CaffeineVertexCache.java#L58) fixes the bug.
The [discussion linked](https://github.com/ben-manes/caffeine/discussions/757) in a comment there contains an answer from the author of caffeeine who mentions that:

> `Runnable::run` [...] works fine for many users and our non-concurrent tests use that for simplicity.

Unfortunately, @ministat mentioned in that discussion that the performance suffers without this setting, so I'm not sure whether we just want to remove it again.

### Stack Trace

```
java.lang.IllegalArgumentException: Connection constraint does not exist for given Edge Label [EDGE_LABEL], outgoing Vertex Label [OUT_VERTEX] and incoming Vertex Label [IN_VERTEX]
	at org.janusgraph.core.schema.DisableDefaultSchemaMaker.makeConnectionConstraint(DisableDefaultSchemaMaker.java:70)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.checkConnectionConstraintOrCreateConnectionConstraint(StandardJanusGraphTx.java:776)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addEdge(StandardJanusGraphTx.java:788)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addEdge(StandardJanusGraphTx.java:780)
	at org.janusgraph.graphdb.vertices.AbstractVertex.addEdge(AbstractVertex.java:188)
	at org.janusgraph.graphdb.vertices.AbstractVertex.addEdge(AbstractVertex.java:45)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddEdgeStep.map(AddEdgeStep.java:122)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddEdgeStep.map(AddEdgeStep.java:48)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.ScalarMapStep.processNextStart(ScalarMapStep.java:40)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:235)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.CoalesceStep.flatMap(CoalesceStep.java:58)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:55)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:235)
	at org.apache.tinkerpop.gremlin.server.util.TraverserIterator.fillBulker(TraverserIterator.java:69)
	at org.apache.tinkerpop.gremlin.server.util.TraverserIterator.hasNext(TraverserIterator.java:56)
	at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.handleIterator(TraversalOpProcessor.java:302)
	at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.lambda$iterateBytecodeTraversal$0(TraversalOpProcessor.java:222)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by porunov** [comment] 2023-03-09 16:36
Thanks @FlorianHockmann for reporting the issue. I didn't investigate that yet, but perhaps @ben-manes or @ministat know more about `.executor(Runnable::run)` problem in Caffeine cache 2.9.3.

**Comment by ben-manes** [comment] 2023-03-09 17:12
Sadly I don't know the Janus code base to make an informed comment. From the stacktrace I wouldn't know how the cache is involved, except that the executor change means that the `removalListener` is performed on the calling thread. If that is evicting an entry that is assumed present and the executor delays that slightly to avoid the race, then this fix only masks a more serious bug. The cache may evict any entry as it is a transient data store, unless that entry is [pinned](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries), so assuming a newly added one must be present is wrong. That would be wrong for LRU/FIFO under a high insert load (as caller might be context switched out), and more so for Caffeine's policy (W-TinyLFU) which is adaptive to the workload characteristics (e.g. MRU is ideal for scans / loopy access patterns).

Usually the main concern with using the default executor, `ForkJoinPool.commonPool()`, is that `CompletableFuture` often runs on it and may block the thread to perform I/O. That exhausts the pool since it is designed for CPU intensive work, making it a bad fit (whereas Loom's virtual threads are ideal for I/O). Since it is a JVM-wide pool then an accidental usage can cause performance issues elsewhere, so using a same-thread executor can be preferred. FJP has also had its fair share of bugs due to the complexity of a work stealing algorithm and concurrency.

My guess is there is an incorrect assumption that should be fixed. Switching executors looks fine to me, but I'm afraid it just makes the real bug harder to reproduce.

**Comment by FlorianHockmann** [comment] 2023-03-13 14:04
Thanks a lot for the detailed answer, @ben-manes! That sounds to me like it makes more sense to stick with the executor as we have it configured right now to avoid these possible performance problems with the `ForkJoinPool`.

And it also looks like @rngcntr found the underlying problem in #3659 🎉

**Closed** 2023-03-20 08:55 UTC
Labels: kind/bug/possible, area/core
