### ISSUE TITLE
Re-opening "Janusgraph intermittently fails to create schema in Cassandra #620"

### ISSUE THREAD

**Issue by AnnuSharma** [JanusGraph/janusgraph#644] opened 2017-10-16 17:54 UTC
Could we please re-open issue #620 ?

**Comment by robertdale** [comment] 2017-10-16 18:21
Can you replicate the problem without kubernetes?
In either case, you will need to provide repeatable steps so that someone can independently reproduce the problem.

**Comment by pluradj** [comment] 2017-10-16 23:46
duplicate of #620, please just continue the conversation over there.

**Closed by pluradj** 2017-10-16 23:46 UTC
