### ISSUE TITLE
JanusGraphIoRegistry support of multiple serializer versions

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#420] opened 2017-07-19 19:02 UTC
Currently, there is only one JanusGraphIoRegistry.  There are older v1 of serializers. Then there are newer v2 of serializers.  For instance, there are GraphSON 1.0 and GraphSON 2.0.  Unfortunately, something like Geoshape is hardcoded in JanusGraphSONModule (to which JanusGraphIoRegistry delegates) to use GeoshapeGsonSerializerV1 .  I don't know the story behind Geoshape support for GraphSON 1.0. I could not get a remote client to work with a gremlin server with what's there.

However, if JanusGraphSONModule registers Geoshape with GeoshapeGsonSerializerV2d0, it all works wonderfully.

I propose that JanusGraphIoRegistry is split into v1 and v2 support much like TinkerIoRegistry is split into V1d0 and V2d0.

See also 
- https://groups.google.com/forum/#!topic/janusgraph-users/RswTmVraChg
- http://tinkerpop.apache.org/docs/3.2.5/dev/io/#graphson-2d0

**Comment by sjudeng** [comment] 2017-07-19 20:50
Not sure if it's relevant but recently-merged #376 (which added the support for GraphSON 2.0) included [some tests](https://github.com/JanusGraph/janusgraph/blob/78bbe5aa65dc2f31e13a004fa21a213de2741cc4/janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphIoTest.java#L77-L82) for GraphSON 1.0/2.0 IO.

**Comment by robertdale** [comment] 2017-07-20 15:45
@sjudeng It is relevant. Note that only the [v1 serializers are registered with JanusGraphSONModule](https://github.com/JanusGraph/janusgraph/pull/376/files#diff-4a920cb0f4947a2678963f6822821a9fR53) (hence JanusGraphIoRegistry).  When using the GraphSONMessageSerializerGremlinV2d0, Geoshape is still locally serialized as GraphSON 1.0 which uses the `@class` key to determine type.  When v2 deserializes, the Geoshape is missing the v2 `@type` key to determine type, thus is deserialized as a Map.

**Comment by sjudeng** [comment] 2017-07-20 18:15
Got it. Your approach of separate JanusGraphIoRegistry sounds good to me. We'll have to add a V3d0 when we update to TinkerPop 3.3.

Separately it sounded like you weren't able to get 1.0 serialization to work properly through gremlin server? Is this a separate (bug) issue?

**Comment by smcquillan** [comment] 2017-08-15 18:34
@sjudeng @amcp While testing reading  back data from Cassandra which had previously been written by Titan I encountered problems deserialising Geoshape objects. Initially I thought this would be fixed by #376 and it was in part.

However, while testing I noticed that the latitude and longitude values being deserialised by JanusGraph didn't match those original written by Titan. I did some testing and I think the problem is that there's a bug in the repositioning of the buffer. I've pushed up a change on a private branch [geoshapePosition](https://github.com/JanusGraph/janusgraph/compare/master...smcquillan:geoshapePosition) which fixed the issue in my environment.

Its getting late in the UK now, but I can open a pull request tomorrow if you agree its a problem.

**Comment by sjudeng** [comment] 2017-08-16 00:11
@smcquillan Wow great find. Updates look good to me, please do submit a PR. Does the existing unit test ([SerializerTest#testLegacyPointSerialization](https://github.com/JanusGraph/janusgraph/blob/78bbe5aa65dc2f31e13a004fa21a213de2741cc4/janusgraph-test/src/test/java/org/janusgraph/graphdb/serializer/SerializerTest.java#L380)) still pass? Surprised it passed before given your finding. Can you add another test or maybe update the current one if that makes sense to reproduce the issue.

**Closed** 2017-09-17 02:45 UTC
