### ISSUE TITLE
Text.textContainsFuzzy is causing problem for text containing hyphen

### ISSUE THREAD

**Issue by vivekweb2013** [JanusGraph/janusgraph#1939] opened 2020-01-25 17:34 UTC
In my spring-boot app I'm using the JanusGraph 0.4.0 as in-memory database.
I've observed that Text.textContainsFuzzy is causing problem when matching query and property value contains hyphen character

Say for example I've below vertices with name property
```
V1 => {name: "abc-test"}
V2 => {name: "abc-another-test"}
V3 => {name: "abc-onemore-test"}
```

When I use the below query
```
g.V().has("name", Text.textContainsFuzzy("abc-test")).toList();
The result is empty
```

But when I do `Text.textContainsFuzzy("abc-")` I get all the vertices.

- Version: 0.4.0
- Storage Backend: NA
- Mixed Index Backend: NA

**Comment by biyuhao** [comment] 2020-02-28 17:12
From the doc [search-predicates](https://docs.janusgraph.org/index-backend/search-predicates/)

> textContainsFuzzy: is true if (at least) one word inside the text string is similar to the query String (based on Levenshtein edit 

So, your query string `abc-test` or `abc-` is not tokenized, and it will be compared with `abc`, `another`, `onemore`, `test` as a term by LevenshteinDistance in `Text#isFuzzy()`.

Then, let's take a look
`abc-another-test` -> {"abc", "another", "test"}
`abc-` matches `abc` return true

`abc-onemore-test` -> {"abc", "onemore", "test"}
`abc-test` does not match `abc`
`abc-test` does not match `onemore`
`abc-test` does not match `test`
so, it will return false.

**Comment by FlorianHockmann** [comment] 2020-03-02 12:06
Thanks for the explanation, @biyuhao! So, this seems to work as intended and it's simply a usage error.

@vivekweb2013: If you think that the docs could be improved to make this behaviour more clear, then you can update the issue to suggest that. For now, I'm closing this as there is no bug.

**Closed by FlorianHockmann** 2020-03-02 12:06 UTC
Labels: kind/bug/possible
