### ISSUE TITLE
GC error : Bulk loading  data using hadoop graph method

### ISSUE THREAD

**Issue by liuyt-15** [JanusGraph/janusgraph#1496] opened 2019-03-18 08:12 UTC
I meet a error when bulkloading data using hadoop method,error log as follows:

```
 ERROR org.apache.spark.util.SparkUncaughtExceptionHandler  - Uncaught exception in thread Thread[Executor task launch worker-37,5,main]
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.<init>(NonBlockingHashMapLong.java:471)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.resize(NonBlockingHashMapLong.java:758)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.putIfMatch(NonBlockingHashMapLong.java:621)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.copy_slot(NonBlockingHashMapLong.java:956)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.help_copy_impl(NonBlockingHashMapLong.java:830)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.access$300(NonBlockingHashMapLong.java:402)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong.help_copy(NonBlockingHashMapLong.java:396)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong.access$1100(NonBlockingHashMapLong.java:79)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.putIfMatch(NonBlockingHashMapLong.java:600)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong$CHM.access$100(NonBlockingHashMapLong.java:402)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong.putIfMatch(NonBlockingHashMapLong.java:317)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong.put(NonBlockingHashMapLong.java:273)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong.put(NonBlockingHashMapLong.java:379)
        at org.cliffc.high_scale_lib.NonBlockingHashMapLong.put(NonBlockingHashMapLong.java:79)
        at org.janusgraph.graphdb.transaction.vertexcache.GuavaVertexCache.add(GuavaVertexCache.java:100)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.connectRelation(StandardJanusGraphTx.java:717)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addEdge(StandardJanusGraphTx.java:704)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addVertex(StandardJanusGraphTx.java:528)
        at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsTransaction.addVertex(JanusGraphBlueprintsTransaction.java:123)
        at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:129)
        at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:47)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddVertexStartStep.processNextStart(AddVertexStartStep.java:86)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:200)
        at org.apache.tinkerpop.gremlin.process.computer.bulkloading.IncrementalBulkLoader.getOrCreateVertex(IncrementalBulkLoader.java:55)
        at org.apache.tinkerpop.gremlin.process.computer.bulkloading.BulkLoaderVertexProgram.executeInternal(BulkLoaderVertexProgram.java:210)
        at org.apache.tinkerpop.gremlin.process.computer.bulkloading.BulkLoaderVertexProgram.execute(BulkLoaderVertexProgram.java:197)
        at org.apache.tinkerpop.gremlin.spark.process.computer.SparkExecutor.lambda$null$5(SparkExecutor.java:118)
        at org.apache.tinkerpop.gremlin.spark.process.computer.SparkExecutor$$Lambda$248/274533952.apply(Unknown Source)
        at org.apache.tinkerpop.gremlin.util.iterator.IteratorUtils$3.next(IteratorUtils.java:247)
        at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)
15:26:16 WARN  org.janusgraph.diskstorage.idmanagement.ConsistentKeyIDAuthority  - Temporary storage exception while acquiring id block - retrying in PT0.6S: org.janusgraph.diskstorage.TemporaryBackendException: Wrote claim for id block [220001, 230001) in PT41.417S => too slow, threshold is: PT0.3S
15:26:16 WARN  org.apache.spark.rpc.netty.NettyRpcEndpointRef  - Error sending message [message = Heartbeat(driver,[Lscala.Tuple2;@21252ee6,BlockManagerId(driver, localhost, 33785))] in 1 attempts
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
        at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:48)
        at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:63)
        at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:76)
        at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:101)
        at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:449)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply$mcV$sp(Executor.scala:470)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:470)
        at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:470)
        at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1765)
        at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:470)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:107)
        at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
        ... 14 more
```

**Comment by FlorianHockmann** [comment] 2019-03-18 09:42
This is most likely not a bug but a configuration problem as you got an `OutOfMemoryError`. Increasing the heap size could help here, but it's hard to tell without knowing more about your configuration, data and the job you're executing.

You can post on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) if you need help with debugging this. Please add more information there in that case about your job, data, and configuration (config files + JVM settings could be helpful).
We really only use issues for bug reports and feature requests. So, I'm closing this.

**Closed by FlorianHockmann** 2019-03-18 09:42 UTC
