### ISSUE TITLE
Remove redundant dependency on org.apache.solr:solr-core

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#310] opened 2017-06-08 11:17 UTC
When you want to use both solr and embeded lucene index backend (e.g. one for production, other for running tests), you need to specify two components on your maven/gradle dependencies list:

```
dependencies {
    compile 'org.janusgraph:janusgraph-solr:0.1.0'    // adds redundant transitive depency to lucene 5.x
    compile 'org.janusgraph:janusgraph-lucene:0.1.0'  // uses lucene 4.x
}
```

But then the embeded lucene stops working (you get AbstractMethod errors) due to version discrepancies between lucene 4.x and 5.x.

Inspecting the dependency tree shows the problem:

**+--- org.janusgraph:janusgraph-solr:0.1.0**
|    +--- org.janusgraph:janusgraph-core:0.1.0 (*)
|    +--- org.apache.solr:solr-solrj:5.2.1
|    |    +--- commons-io:commons-io:2.4
|    |    +--- org.apache.httpcomponents:httpclient:4.4.1 (*)
|    |    +--- org.apache.httpcomponents:httpcore:4.4.1
|    |    +--- org.apache.httpcomponents:httpmime:4.4.1
|    |    +--- org.apache.zookeeper:zookeeper:3.4.6
|    |    +--- org.codehaus.woodstox:stax2-api:3.1.4
|    |    +--- org.codehaus.woodstox:woodstox-core-asl:4.4.1
|    |    +--- org.noggit:noggit:0.6
|    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.25
**|    +--- org.apache.solr:solr-core:5.2.1
|    |    +--- org.apache.lucene:lucene-analyzers-common:5.2.1
|    |    |    \--- org.apache.lucene:lucene-core:5.2.1**
|    |    +--- org.apache.lucene:lucene-analyzers-kuromoji:5.2.1
|    |    +--- org.apache.lucene:lucene-analyzers-phonetic:5.2.1
|    |    +--- org.apache.lucene:lucene-backward-codecs:5.2.1
|    |    +--- org.apache.lucene:lucene-codecs:5.2.1
|    |    +--- org.apache.lucene:lucene-core:5.2.1
|    |    +--- org.apache.lucene:lucene-expressions:5.2.1
|    |    +--- org.apache.lucene:lucene-grouping:5.2.1
|    |    +--- org.apache.lucene:lucene-highlighter:5.2.1
|    |    +--- org.apache.lucene:lucene-join:5.2.1
|    |    +--- org.apache.lucene:lucene-memory:5.2.1
|    |    +--- org.apache.lucene:lucene-misc:5.2.1
|    |    +--- org.apache.lucene:lucene-queries:5.2.1
|    |    +--- org.apache.lucene:lucene-queryparser:5.2.1
|    |    |    +--- org.apache.lucene:lucene-core:5.2.1
|    |    |    +--- org.apache.lucene:lucene-queries:5.2.1
|    |    |    \--- org.apache.lucene:lucene-sandbox:5.2.1
|    |    +--- org.apache.lucene:lucene-spatial:5.2.1
|    |    |    +--- org.apache.lucene:lucene-core:5.2.1
|    |    |    +--- org.apache.lucene:lucene-misc:5.2.1
|    |    |    +--- org.apache.lucene:lucene-queries:5.2.1
|    |    |    \--- com.spatial4j:spatial4j:0.4.1
|    |    +--- org.apache.lucene:lucene-suggest:5.2.1
|    |    +--- org.apache.solr:solr-solrj:5.2.1 (*)
|    |    +--- com.carrotsearch:hppc:0.5.2 -> 0.7.1
|    |    +--- com.google.guava:guava:14.0.1 -> 18.0
|    |    +--- com.google.protobuf:protobuf-java:2.5.0
|    |    +--- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.2 -> 1.3
|    |    +--- com.tdunning:t-digest:3.1
|    |    +--- commons-cli:commons-cli:1.2
|    |    +--- commons-codec:commons-codec:1.10
|    |    +--- commons-collections:commons-collections:3.2.1 -> 3.2.2
|    |    +--- commons-configuration:commons-configuration:1.6 -> 1.10 (*)
|    |    +--- commons-fileupload:commons-fileupload:1.2.1
|    |    +--- commons-io:commons-io:2.4
|    |    +--- commons-lang:commons-lang:2.6
|    |    +--- dom4j:dom4j:1.6.1 (*)
|    |    +--- it.unimi.dsi:fastutil:6.5.11
|    |    +--- javax.servlet:javax.servlet-api:3.1.0
|    |    +--- joda-time:joda-time:2.2
|    |    +--- log4j:log4j:1.2.17
|    |    +--- net.agkn:hll:1.6.0
|    |    +--- org.antlr:antlr-runtime:3.5 -> 3.5.2
|    |    +--- org.apache.hadoop:hadoop-annotations:2.6.0
|    |    +--- org.apache.hadoop:hadoop-auth:2.6.0
|    |    +--- org.apache.hadoop:hadoop-common:2.6.0
|    |    +--- org.apache.hadoop:hadoop-hdfs:2.6.0
|    |    +--- org.apache.httpcomponents:httpclient:4.4.1 (*)
|    |    +--- org.apache.httpcomponents:httpcore:4.4.1
|    |    +--- org.apache.httpcomponents:httpmime:4.4.1
|    |    +--- org.codehaus.woodstox:stax2-api:3.1.4
|    |    +--- org.codehaus.woodstox:woodstox-core-asl:4.4.1
|    |    +--- org.eclipse.jetty:jetty-continuation:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-deploy:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-http:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-io:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-jmx:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-rewrite:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-security:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-server:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-servlet:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-servlets:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-util:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-webapp:9.2.10.v20150310
|    |    +--- org.eclipse.jetty:jetty-xml:9.2.10.v20150310
|    |    +--- org.htrace:htrace-core:3.0.4
|    |    +--- org.noggit:noggit:0.6
|    |    +--- org.ow2.asm:asm:4.1
|    |    +--- org.ow2.asm:asm-commons:4.1
|    |    +--- org.restlet.jee:org.restlet:2.3.0
|    |    +--- org.restlet.jee:org.restlet.ext.servlet:2.3.0
|    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.25
|    +--- javax.servlet:servlet-api:2.5
|    +--- com.spatial4j:spatial4j:0.4.1
|    \--- org.slf4j:slf4j-api:1.7.12 -> 1.7.25
**+--- org.janusgraph:janusgraph-lucene:0.1.0
|    +--- org.janusgraph:janusgraph-core:0.1.0 (*)
|    +--- org.apache.lucene:lucene-core:4.10.4 -> 5.2.1**
|    +--- org.apache.lucene:lucene-analyzers-common:4.10.4 -> 5.2.1 (*)
|    +--- org.apache.lucene:lucene-queryparser:4.10.4 -> 5.2.1 (*)
|    +--- org.apache.lucene:lucene-spatial:4.10.4 -> 5.2.1 (*)
|    \--- org.slf4j:slf4j-api:1.7.12 -> 1.7.25

The  org.apache.lucene:lucene-analyzers-common:4.10.4 needed by embeded lucene gets promoted to version 5.2.1 by automatic version conflict resolution.

To workaround the issue you must explicitly exlcude solr-core from your deps:

```
    compile ("org.janusgraph:janusgraph-solr:0.10") {
        exclude group: 'org.apache.solr', module: 'solr-core'
    }
    compile "org.janusgraph:janusgraph-lucene:0.10"
```

which gives the correct (much shorter) deps tree:

**--- org.janusgraph:janusgraph-solr:0.1.0
|    +--- org.janusgraph:janusgraph-core:0.1.0 (*)
|    +--- org.apache.solr:solr-solrj:5.2.1**
|    |    +--- commons-io:commons-io:2.4
|    |    +--- org.apache.httpcomponents:httpclient:4.4.1 (*)
|    |    +--- org.apache.httpcomponents:httpcore:4.4.1
|    |    +--- org.apache.httpcomponents:httpmime:4.4.1
|    |    +--- org.apache.zookeeper:zookeeper:3.4.6
|    |    +--- org.codehaus.woodstox:stax2-api:3.1.4
|    |    +--- org.codehaus.woodstox:woodstox-core-asl:4.4.1
|    |    +--- org.noggit:noggit:0.6
|    |    \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.25
|    +--- javax.servlet:servlet-api:2.5
|    +--- com.spatial4j:spatial4j:0.4.1
|    \--- org.slf4j:slf4j-api:1.7.12 -> 1.7.25
**+--- org.janusgraph:janusgraph-lucene:0.1.0**
|    +--- org.janusgraph:janusgraph-core:0.1.0 (*)
**|    +--- org.apache.lucene:lucene-core:4.10.4**
|    +--- org.apache.lucene:lucene-analyzers-common:4.10.4
|    |    \--- org.apache.lucene:lucene-core:4.10.4
|    +--- org.apache.lucene:lucene-queryparser:4.10.4
|    |    +--- org.apache.lucene:lucene-core:4.10.4
|    |    +--- org.apache.lucene:lucene-queries:4.10.4
|    |    \--- org.apache.lucene:lucene-sandbox:4.10.4
|    +--- org.apache.lucene:lucene-spatial:4.10.4
|    |    +--- org.apache.lucene:lucene-core:4.10.4
|    |    +--- org.apache.lucene:lucene-queries:4.10.4
|    |    \--- com.spatial4j:spatial4j:0.4.1
|    \--- org.slf4j:slf4j-api:1.7.12 -> 1.7.25

The solr-core dep is redundant, since solr-client is enough to communicate with the server and we do not need to pollute the deps with actual server implementation jars. 

Please fix this in your maven build config.

**Comment by sjudeng** [comment] 2017-06-08 11:26
I added #311 to update Lucene and Solr to their latest version. Can you test this out on that branch to see if the issue is resolved?

**Comment by wojciechwojcik** [comment] 2017-06-09 06:32
In the files changed I can clearly see that the issue is NOT resolved.
The dependency to solr-core is still there. 
I've added a new comment under #311.

**Comment by sjudeng** [comment] 2017-06-09 13:14
I think the underlying issue here is an inconsistency in the Lucene version used in the janusgraph-solr and janusgraph-lucene modules which is fixed in #311. But currently (e.g. in 0.1/master) t's not possible to remove solr-core (the build fails) because janusgraph-solr depends on Lucene 5.

**Comment by sjudeng** [comment] 2017-07-07 03:47
I understand you'd like to keep this issue open to track removal of the solr-core dependency but can we update your title/description to remove reference to the issue of broken embedded Lucene? I think that issue has been fixed with the merged Lucene/Solr version update.

**Comment by wojciechwojcik** [comment] 2017-07-07 05:56
Done

**Closed** 2017-09-21 21:43 UTC
Labels: cleanup, solr
