### ISSUE TITLE
TinkerPop tests fail for CQL

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#1901] opened 2019-12-05 23:33 UTC
From stack trace it looks like CQL container doesn't start on my system during the TinkerPop tests execution (logs: `ContainerLaunchException: Container startup failed`). I don't know why it doesn't start but it prevents me from executing all TinkerPop tests for JanusGraph.

For confirmed bugs, please report:
- Version: 0.5.0-SNAPSHOT
- Storage Backend: CQL
- Steps to Reproduce: 

1) Install docker

2) Follow next steps to run TinkerPop tests:
```
git clone https://github.com/JanusGraph/janusgraph
cd janusgraph
reset --hard 6929fc7540c86e06768781b31efc75548827d2ca
git remote add FlorianHockmann https://github.com/FlorianHockmann/janusgraph
git fetch FlorianHockmann
git merge FlorianHockmann/Issue_1856_DockerBuild
docker-build/docker-build.sh -p
```

### Stack Trace

Top of the stack trace:
```
[INFO]  T E S T S^M
[INFO] -------------------------------------------------------^M
        ^[[37m^[[1mℹ︎ Checking the system...^[[0m^[[0m^M
        ^[[32m✔ Docker version should be at least 1.6.0^[[0m^M
        ^[[32m✔ Docker environment should have more than 2GB free disk space^[[0m^M
        ^[[37m^[[1mℹ︎ Checking the system...^[[0m^[[0m^M
        ^[[32m✔ Docker version should be at least 1.6.0^[[0m^M
        ^[[32m✔ Docker environment should have more than 2GB free disk space^[[0m^M
[INFO] Running org.janusgraph.blueprints.cql.process.CQLComputerTest^M
[ERROR] Tests run: 718, Failures: 718, Errors: 0, Skipped: 0, Time elapsed: 192.083 s <<< FAILURE! - in org.janusgraph.blueprints.cql.process.CQLComputerTest^M
[ERROR] testMessagePassingOut  Time elapsed: 182.386 s  <<< FAILURE!^M
org.opentest4j.MultipleFailuresError: ^M
Multiple Failures (2 failures)^M
        org.testcontainers.containers.ContainerLaunchException: Container startup failed^M
        java.lang.NullPointerException: <no message>^M
^M
[ERROR] shouldSucceedWithProperTraverserRequirements  Time elapsed: 0.7 s  <<< FAILURE!^M
org.opentest4j.MultipleFailuresError: ^M
Multiple Failures (2 failures)^M
        java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager^M
        java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
```
Bottom of the stack trace:
```
[ERROR]   StarGraphTest.shouldHandleSelfLoops Multiple Failures (2 failures)
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
[ERROR]   StarGraphTest.shouldHashAndEqualsCorrectly Multiple Failures (2 failures)
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
[ERROR]   StarGraphTest.shouldSerializeCorrectlyUsingGryo Multiple Failures (2 failures)
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
[ERROR]   StarGraphTest.shouldValidateThatOriginalAndStarVerticesHaveTheSameTopology Multiple Failures (2 failures)
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
	java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CachingCQLStoreManager
[INFO] 
[ERROR] Tests run: 1739, Failures: 1735, Errors: 0, Skipped: 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JanusGraph: Distributed Graph Database ............. SUCCESS [ 34.574 s]
[INFO] JanusGraph-Core: Core Library for JanusGraph ....... SUCCESS [04:31 min]
[INFO] JanusGraph-Backend-testutils: Collection of Backend tests SUCCESS [01:22 min]
[INFO] JanusGraph CodePipelines CI: Distributed release testing. SUCCESS [03:44 min]
[INFO] janusgraph-server .................................. SUCCESS [  0.281 s]
[INFO] JanusGraph-InMemory: InMemory Backend for JanusGraph SUCCESS [22:48 min]
[INFO] JanusGraph-Test: Test Suite for JanusGraph ......... SUCCESS [  1.198 s]
[INFO] JanusGraph-BerkeleyJE: Distributed Graph Database .. SUCCESS [  02:02 h]
[INFO] JanusGraph-CQL: Distributed Graph Database ......... FAILURE [16:42 min]
[INFO] JanusGraph-Cassandra: Distributed Graph Database ... SKIPPED
[INFO] JanusGraph-HBase: Parent Module .................... SKIPPED
[INFO] JanusGraph-HBase: Version-independent Core ......... SKIPPED
[INFO] JanusGraph-HBase: HBase Server Used by Maven Testing SKIPPED
[INFO] JanusGraph-HBase: 1.x and 2.x Compatibility Shim ... SKIPPED
[INFO] JanusGraph-HBase: Universal binary ................. SKIPPED
[INFO] JanusGraph-ElasticSearch: Distributed Indexing Support SKIPPED
[INFO] JanusGraph-Hadoop: Module .......................... SKIPPED
[INFO] JanusGraph-Bigtable: Google Cloud Bigtable driver .. SKIPPED
[INFO] JanusGraph-Lucene: Indexing Support ................ SKIPPED
[INFO] JanusGraph-Solr: Distributed Indexing Support ...... SKIPPED
[INFO] JanusGraph-All: Complete JanusGraph Distribution ... SKIPPED
[INFO] JanusGraph-Dist: Tar and Zip Archives .............. SKIPPED
[INFO] JanusGraph-Doc: Manual for JanusGraph .............. SKIPPED
[INFO] JanusGraph-Examples: Examples for JanusGraph ....... SKIPPED
[INFO] Example-Common: Common Graph Code for Examples ..... SKIPPED
[INFO] Example-BerkeleyJE: BerkeleyJE Storage, Lucene Index SKIPPED
[INFO] Example-Cassandra: Cassandra Thrift Storage, Elasticsearch Index SKIPPED
[INFO] Example-Cql: Cassandra CQL Storage, Elasticsearch Index SKIPPED
[INFO] Example-HBase: HBase Storage, Solr Index ........... SKIPPED
[INFO] Example-RemoteGraph: Example with RemoteGraph ...... SKIPPED
[INFO] Example-TinkerGraph: Example with TinkerGraph ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:52 h
[INFO] Finished at: 2019-11-20T19:13:29+00:00
[INFO] Final Memory: 117M/2590M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (tinkerpop-test) on project janusgraph-cql: There are test failures.
[ERROR] 
[ERROR] Please refer to /usr/src/janusgraph/janusgraph-cql/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :janusgraph-cql
```

**Comment by farodin91** [comment] 2019-12-10 12:32
I justed executed the CQL TinkerPop directly on my machine and they work perfectly. I think it is more a problem with the docker test image from the PR #1888, because the tests also fail on my machine with the test image. I will check what the problem is with the created image. Therefore, i will close this issue.

**Closed by farodin91** 2019-12-10 12:32 UTC
Labels: area/tinkerpop, kind/bug/possible, storage/cassandra

**Comment by porunov** [comment] 2019-12-11 05:36
@farodin91 It would be really helpful because I don't have other abilities to execute TinkerPop tests (running tests with TinkerPop tests by 'mvn clean install -Dtest.skip.tp=false' always fails on my system). 
I will try to execute TinkerPop only tests on master branch, and provide the result later.

**Comment by farodin91** [comment] 2019-12-11 07:06
I did executed the CQL Tinkerpop tests on the master branch using my plain system and the tool from PR #1888 and it just failed on the tool from the pr.

**Comment by porunov** [comment] 2019-12-11 15:10
CQL TinkerPop tests passed when executing TinkerPop only tests. I am still waiting for the tests to be finished (currently `Building JanusGraph-Cassandra: Distributed Graph Database 0.5.0-SNAPSHOT [10/31]`). I will provide report after the tests are finished. I don't have enough resources to start parallel testing of #1905 , so I will start tests for that PR after current tests are finished.

**Comment by porunov** [comment] 2019-12-11 20:42
All TinkerPop only tests passed for current master branch (`mvn clean install -Dtest.skip.tp=false -DskipTests=true`) on my system.
Starting tests for #1905
