### ISSUE TITLE
All mixed index deleted in Elasticsearch when drop graph

### ISSUE THREAD

**Issue by CysOrion** [JanusGraph/janusgraph#4300] opened 2024-03-07 23:33 UTC
Please include configurations and logs if available.

For confirmed bugs, please report:

- Version: 0.6.0 
- Storage Backend: CQL
- Mixed Index Backend: Elasticsearch
- Link to discussed bug: 
- Expected Behavior: Only the mixed index of the drop graph should be removed
- Current Behavior: 
When delete a graph in gremlin console, all mixed index in Elasticsearch deleted.
- Steps to Reproduce:
1. Run the following command to drop a graph.
2. Observe the indices in Elasticsearch

The behavior is not consistent, it occurs randomly. I am awarethere is a newer release, may I know if this issue is fixed?
I used the following command to drop the graph:

```graph_name = "graph_to_drop"

drop_graph = ConfiguredGraphFactory.open(graph_name)
mgmt = drop_graph.openManagement()
openInstances = mgmt.getOpenInstances().toList()
if (openInstances.size() > 1) {
    for (int index = 0; index < openInstances.size(); index++) {
        instance_id = openInstances.get(index)
        if (!instance_id.contains("current")) {
            mgmt.forceCloseInstance(instance_id)
        }
    }
}
mgmt.getOpenInstances()
mgmt.commit()
mgmt.getOpenInstances()

drop_graph.traversal().tx().rollback()
ConfiguredGraphFactory.drop(graph_name) ```

**Comment by FlorianHockmann** [comment] 2024-03-08 07:49
I think this is really something that should be fixed in 1.0.0. The problem before 1.0.0 was that JanusGraph used the same mixed index in Elasticsearch for all graphs created by the `ConfiguredGraphFactory`. [This has been changed in 1.0.0.](https://docs.janusgraph.org/changelog/#configuredgraphfactory-now-creates-separate-indices-per-graph-in-elasticsearch) JanusGraph now uses the `graph.graphname` as the name of the index for Elasticsearch by default.

So, before 1.0.0, JanusGraph couldn't only delete mixed indices of one graph since they weren't stored separately.
I'm just wondering why this isn't happening consistently for you. Do you maybe simply have some indices that are not present in all of your graphs?

But in general, please check whether this works as expected with JanusGraph 1.0.0.

**Comment by CysOrion** [comment] 2024-03-10 09:19
@FlorianHockmann Thank you so much for your reply! From the release note you referenced it says same Elasticsearch index is used for all graphs if the same index names were used across different graphs, well in my case I always use unique index name for each graph. If delete graph works properly, it should only delete the mixed index that matches the names, which are the indices belongs to the graph, right?

And yes, this problem happens randomly for me, because there are times where ConfiguredGraphFactory.drop() deleted the correct indices, so I guess it was a bug?

Since the graph database is used in production, updating to 1.0.0 is something we want to avoid. We will still test this in 1.0.0 in a testing environment. 

Do you know if there is a configuration that can disable mixed index deletion? That would solve the issue since we are ok to delete the indices manually. I looked through the configuration and I cannot find it, so maybe you can enlighten me, thanks!

**Comment by porunov** [comment] 2024-03-10 11:10
If you have a test which reproduces the problem it would be much more efficient and faster to fix. 
Some things to notice: 
1. Any release below 1.0 are EOL. Meaning new bug fixes are not pushed automatically to those releases. However, maintainers don’t object to backport those fixes if users open PRs on the relative branches (v0.6 in your case).
2. As far as I remember JanusGraph below 1.0 didn’t have ability to remove the indices (a.k.a. tables) from ElasticSearch. Thus, if the bug on JanusGraph side then it would remove mixed index from the schema only and not delete actual data from ElasticSearch. Thus, as a workaround, you can create your missing indices with the same names you used and they will use the existing data from ElasticSearch (unless you manually removed data from ElasticSearch).

**Comment by CysOrion** [comment] 2024-03-17 10:22
I scrolled through the issue list in this repo and found a post that has similar bug:

[https://github.com/JanusGraph/janusgraph/issues/2433#issuecomment-878311810](url)

He provided a workaround which is removing Mixed index backend in graph configuration, I will use that work around for now.

**Comment by CysOrion** [comment] 2024-03-17 10:23
#2433

**Closed** 2024-03-20 02:26 UTC
Labels: kind/bug/possible, index/elasticsearch
