### ISSUE TITLE
JanusGraphCleanup exception with embedded Lucene on Windows

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#309] opened 2017-06-08 10:58 UTC
Configuration
        
```
# storage backend
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=cassandrathrift
storage.hostname=192.168.99.100
schema.default=none

# index backend
index.search.backend=lucene
# path is relative to pwd
index.search.directory=build/searchindex

```
When trying to do:
(https://stackoverflow.com/questions/19477443/how-to-delete-graph-in-titan-with-cassandra-storage-backend)

```
        JanusGraphFactory.open(configuration);
        janusGraph.close();
        JanusGraphCleanup.clear(janusGraph);
```

There is always an exception thrown:
```
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Could not delete lucene directory: <path>\build\searchindex
	at org.janusgraph.diskstorage.lucene.LuceneIndex.clearStorage(LuceneIndex.java:666)
	at org.janusgraph.diskstorage.Backend.clearStorage(Backend.java:596)
	at org.janusgraph.core.util.JanusGraphCleanup$1.call(JanusGraphCleanup.java:51)
	at org.janusgraph.core.util.JanusGraphCleanup$1.call(JanusGraphCleanup.java:48)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
	... 18 more
Caused by: java.io.IOException: Unable to delete directory <path>build\searchindex\indexBynameshortdescriptionTEXT.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1473)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2183)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1585)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1467)
	at org.janusgraph.diskstorage.lucene.LuceneIndex.clearStorage(LuceneIndex.java:664)
	... 23 more

```

It seems that lucene is holding locks on files as long as JVM is running. Trying to delete the index directory using generic FileUtils will always end up in IOException.

See also: https://stackoverflow.com/questions/21901499/why-i-cannot-delete-index-directories-in-lucene-after-i-make-the-searcher-null

**Comment by sjudeng** [comment] 2017-07-30 22:37
Is this on Windows? I'm not able to reproduce the issue in Linux. I tried JanusGraph 0.1.0, 0.1.1 and master.

```
cat > conf/test.properties << EOF
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=cassandrathrift
storage.hostname=localhost
schema.default=none
index.search.backend=lucene
index.search.directory=build/searchindex
EOF

docker run --rm --name janus-cassandra -p 9042:9042 -p 9160:9160 -e CASSANDRA_START_RPC=true -d cassandra:2

./bin/gremlin.sh
...
gremlin> graph = JanusGraphFactory.open('conf/test.properties')
==>standardjanusgraph[cassandrathrift:[localhost]]
gremlin> hdfs.exists('conf/build/searchindex')
==>true
gremlin> hdfs.ls('conf/build/searchindex')
gremlin> GraphOfTheGodsFactory.load(graph)
==>null
gremlin> hdfs.ls('conf/build/searchindex')
==>rwxr-xr-x test test 4096 (D) vertices
==>rwxr-xr-x test test 4096 (D) edges
gremlin> graph.close()
==>null
gremlin> import org.janusgraph.core.util.JanusGraphCleanup
...
gremlin> JanusGraphCleanup.clear(graph)
==>null
gremlin> hdfs.exists('conf/build/searchindex')
==>false
```

**Comment by wojciechwojcik** [comment] 2017-07-31 08:38
Yes, you are right, this is on Windows, where open file handle can be enough to prevent you from deleting a file or folder.
Linux will not produce the same behavior, because as root you can delete any file even if it is currently open.

**Comment by sjudeng** [comment] 2017-07-31 11:45
It does work as well with non-root user in Linux.

**Comment by robertdale** [comment] 2017-09-09 12:13
Unable to reproduce on Linux, but did verify that after `graph.close()` there are no open file handles to lucene indexes. 

@wojciechwojcik Can you provide complete steps to reproduce? Start with unzipping the distribution.  Simply opening the graph configuration does not create indexes. Also, I notice that you have `gremlin.graph`.  Are you also also running gremlin-server?

**Comment by wojciechwojcik** [comment] 2017-09-11 05:45
@robertdale as @sjudeng already noticed and as the issue title says, this only happens on Windows. There are no steps to reproduce on Linux.

**Comment by robertdale** [comment] 2017-09-11 11:19
Unable to reproduce. See attached screenshot.  Please provide environment settings and **all steps to reproduce**.
![screenshot_2017-09-11_07-17-07](https://user-images.githubusercontent.com/122206/30272223-70ca88aa-96c1-11e7-871f-b5d94c43d014.png)

**Comment by wojciechwojcik** [comment] 2017-09-11 11:25
@robertdale Try exactly the same what you tried, but from Java code. I am not using gremlin console or gremlin server.

**Comment by wojciechwojcik** [comment] 2017-09-11 11:26
Also not sure if that matters, but you are using inmemory graph, while my configuration is using cassandra.

**Comment by wojciechwojcik** [comment] 2017-09-11 11:28
Windows 7, Java 1.8.

**Comment by robertdale** [comment] 2017-09-11 13:08
Could not reproduce with `cassandrathrift` backend. Closing issue.

Please reopen if you can provide accurate, repeatable steps to reproduce and a failing test case.

**Closed by robertdale** 2017-09-11 13:08 UTC
Labels: bug
