### ISSUE TITLE
Date Query not working in janusgraph

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1253] opened 2018-09-13 06:47 UTC
I have declared date type field in janusgraph. While inserting data only date converted into long type is accepted. If but in searching seached with long date type is not supported

**Comment by pluradj** [comment] 2018-09-13 15:21
Please provide more specific details on how you declared the date field and what queries you ran

**Comment by pluradj** [comment] 2018-09-14 17:15
closing as duplicate of #1254

**Closed by pluradj** 2018-09-14 17:15 UTC
