### ISSUE TITLE
When mixed index query contains quoted "\\" character IllegalArgumentException is thrown

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#314] opened 2017-06-08 11:45 UTC
Minor issue

When trying to do:

```
String queryString = "v.\"short_description\\\""
JanusGraphIndexQuery indexQuery = janusGraph.indexQuery(INDEX_NAME, queryString);
```

The exception is thrown:
```
java.lang.IllegalArgumentException: Found reference to empty key at position [0]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.janusgraph.graphdb.database.IndexSerializer.executeQuery(IndexSerializer.java:646)
	at org.janusgraph.graphdb.query.graph.IndexQueryBuilder.execute(IndexQueryBuilder.java:193)
	at org.janusgraph.graphdb.query.graph.IndexQueryBuilder.vertices(IndexQueryBuilder.java:212)
	at com.ibm.udg.labbook.persistence.janus.search.IndexQueryExecutor.executeQuery(IndexQueryExecutor.java:41)
```

In our case the query string should really be
String queryString = "v.\"short_description\""

but the exception we got was not exactly helpful in finding the problem.
Also I do not see a documentation stating that special characters cannot be part of direct index query.

**Comment by robertdale** [comment] 2017-09-11 13:20
`"v.\"short_description\\\""` evaluates to `v."short_description\"` not `v."short_description"`.   Does using `"v.\"short_description\""` solve your problem?

**Comment by wojciechwojcik** [comment] 2017-09-11 13:33
Yes it does, no it is not the point here. 
The point is that if you use any special character in the query like `\\` you like get some meaningless exception.

**Comment by robertdale** [comment] 2017-09-11 15:25
Technically, it has nothing to do with special characters. http://docs.janusgraph.org/latest/direct-index-query.html#_property_key_names

> Names of property keys that contain non-alphanumeric characters must be placed in quotation marks to ensure that the query is parsed correctly.

Unable to reproduce your `empty key` error. Please provide complete steps to reproduce or failing test case.

```
gremlin> graph = JanusGraphFactory.open('conf/janusgraph-cassandra-es.properties')
==>standardjanusgraph[cassandrathrift:[127.0.0.1]]
gremlin> mgmt = graph.openManagement();
==>org.janusgraph.graphdb.database.management.ManagementSystem@126f8f24
gremlin> text = mgmt.makePropertyKey("text").dataType(String.class).make();
==>text
gremlin> mgmt.buildIndex("vertexByText", Vertex.class).addKey(text).buildMixedIndex("search");
==>vertexByText
gremlin> mgmt.commit();
==>null
gremlin> mgmt.awaitGraphIndexStatus(graph, 'vertexByText').call()
==>GraphIndexStatusReport[success=false, indexName='vertexByText', targetStatus=REGISTERED, notConverged={text=ENABLED}, converged={}, elapsed=PT1M0.217S]
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[cassandrathrift:[127.0.0.1]], standard]
gremlin> g.addV().property('text','farm')
==>v[4144]
gremlin> g.tx().commit()
==>null
gremlin> graph.indexQuery("vertexByText", "v.\"text\":(farm uncle berry)").vertices().forEach{println it}
org.janusgraph.graphdb.query.graph.IndexQueryBuilder$ResultImpl@1144a02b
==>null
gremlin> 
gremlin> graph.indexQuery("vertexByText", "v.\"text\\\":(farm uncle berry)").vertices().forEach{println it}
Found reference to non-existant property key in query at position [0]: text\
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> 
gremlin> graph.indexQuery("vertexByText", "v.\"text\\\"").vertices().forEach{println it}
Found reference to non-existant property key in query at position [0]: text\
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> graph.indexQuery("vertexByText", "v.\"short_description\\\"").vertices().forEach{println it}
Found reference to non-existant property key in query at position [0]: short_description\
Type ':help' or ':h' for help.
Display stack trace? [yN]
```

**Comment by wojciechwojcik** [comment] 2017-09-11 15:37
Keep in mind these defects are fairly dated and were opened against 0.10 release of Janus.
If you cannot reproduce it on latest dev build the better. Sorry but I cannot give you more detailed instructions 3 months after this problem was raised. Feel free to close it.

**Comment by robertdale** [comment] 2017-09-11 15:40
This was tested on 0.1.1. Documentation link is of 0.1.1.  Closing.

**Closed by robertdale** 2017-09-11 15:40 UTC
Labels: bug

**Comment by wojciechwojcik** [comment] 2017-09-28 10:25
The error still occurs, and you were able to reproduce it:

````
gremlin> graph.indexQuery("vertexByText", "v.\"text\\\":(farm uncle berry)").vertices().forEach{println it}
Found reference to non-existant property key in query at position [0]: text\
Type ':help' or ':h' for help.
Display stack trace? [yN]
````

The gremlin console does not print exception by default, that's it.
