### ISSUE TITLE
5.2.2. Property Key Cardinality in Document Example Does Not Work

### ISSUE THREAD

**Issue by jrhayward** [JanusGraph/janusgraph#1262] opened 2018-09-19 20:54 UTC
5.2.2. Property Key Cardinality
When attempting to use this code from the example
```
mgmt = graph.openManagement()
birthDate = mgmt.makePropertyKey('birthDate').dataType(Long.class).cardinality(Cardinality.SINGLE).make()
name = mgmt.makePropertyKey('name').dataType(String.class).cardinality(Cardinality.SET).make()
sensorReading = mgmt.makePropertyKey('sensorReading').dataType(Double.class).cardinality(Cardinality.LIST).make()
mgmt.commit()
 
```
The following  step
`birthDate = mgmt.makePropertyKey('birthDate').dataType(Long.class).cardinality(Cardinality.SINGLE).make()
`produces error
`No such property: SINGLE for class: org.apache.tinkerpop.gremlin.structure.VertexProperty$Cardinality
`To make it work you must use ...
`birthDate = mgmt.makePropertyKey('birthDate').dataType(Long.class).cardinality(SINGLE).make()
`
Where the Cardinality qualifier is not used (ie: SINGLE rather than Cardinality.SINGLE)

**Comment by pluradj** [comment] 2018-09-19 21:11
Thanks for the issue. It is a duplicate of #1222 

A valid workaround is to use the fully-qualified `org.janusgraph.core.Cardinality.SINGLE`

**Closed by pluradj** 2018-09-19 21:11 UTC
