### ISSUE TITLE
GremlinServer  StackOverflowError

### ISSUE THREAD

**Issue by boliza** [JanusGraph/janusgraph#1114] opened 2018-06-14 07:10 UTC
Tranversal is: g.V(49280L).properties()

```java
67521305 [gremlin-server-exec-5] WARN  org.apache.tinkerpop.gremlin.server.handler.HttpGremlinEndpointHandler  - Invalid request - responding with 500 Internal Server Error and Error encountered evaluating script:
g.V(49280L).properties()
java.lang.StackOverflowError
        at com.google.common.cache.LocalCache$Segment.getLiveEntry(LocalCache.java:2721)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2758)
        at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:3926)
        at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:4733)
        at org.janusgraph.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:71)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getVertex(StandardJanusGraphTx.java:387)
        at org.janusgraph.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:53)
        at org.janusgraph.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:43)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.it(CacheVertexProperty.java:58)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.longId(CacheVertexProperty.java:83)
        at org.janusgraph.graphdb.internal.AbstractElement.hasId(AbstractElement.java:115)
        at org.janusgraph.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:63)
        at org.janusgraph.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:46)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.it(CacheVertexProperty.java:58)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.longId(CacheVertexProperty.java:83)
        at org.janusgraph.graphdb.internal.AbstractElement.hasId(AbstractElement.java:115)
        at org.janusgraph.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:63)
        at org.janusgraph.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:46)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.it(CacheVertexProperty.java:58)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.longId(CacheVertexProperty.java:83)
        at org.janusgraph.graphdb.internal.AbstractElement.hasId(AbstractElement.java:115)
        at org.janusgraph.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:63)
        at org.janusgraph.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:46)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.it(CacheVertexProperty.java:58)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.longId(CacheVertexProperty.java:83)
        at org.janusgraph.graphdb.internal.AbstractElement.hasId(AbstractElement.java:115)
        at org.janusgraph.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:63)
        at org.janusgraph.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:46)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.it(CacheVertexProperty.java:58)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.longId(CacheVertexProperty.java:83)
        at org.janusgraph.graphdb.internal.AbstractElement.hasId(AbstractElement.java:115)
        at org.janusgraph.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:63)
        at org.janusgraph.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:46)
        at org.janusgraph.graphdb.relations.CacheVertexProperty.it(CacheVertexProperty.java:58)
```

**Comment by boliza** [comment] 2018-06-14 07:10
gremlin server config:

```yml
host: 0.0.0.0
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer
graphs: {
  graph: conf/janusgraph-cql-es.properties
}
scriptEngines: {
  gremlin-groovy: {
    plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
               org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
               org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]}},
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI],
    scripts: [scripts/empty-sample.groovy]}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoLiteMessageSerializerV1d0, config: {ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
  - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
```

**Comment by pluradj** [comment] 2018-06-14 15:42
duplicate of #920

**Closed** 2018-09-20 21:35 UTC
Labels: bug
