### ISSUE TITLE
Janusgraph intermittently fails to create schema in Cassandra

### ISSUE THREAD

**Issue by AnnuSharma** [JanusGraph/janusgraph#620] opened 2017-10-12 01:05 UTC
I have been working on a dockerised deployment of Janus graph server with a Cassandra Thrift backend running in the same Kubernetes cluster. Intermittently, the graph server fails to create the keyspace with a timeout error. I have bumped up the client(Janus) as well as server(Cassandra) read/write timeout to upto 30s but still face this issue intermittently. Has this been investigated?

**Comment by robertdale** [comment] 2017-10-12 01:13
Please provide steps to reproduce, relevant configuration files, log files, stacktraces, etc.

**Comment by AnnuSharma** [comment] 2017-10-12 19:09
Hi,

PFA the stacktrace when deploying the janus server on Kubernetes in a Centos based docker container.

Also, attached it the janusgraph properties file containing the configurations. Thanks.


[janusgraph-cassandra-server.properties](https://github.com/JanusGraph/janusgraph/files/1380372/janusgraph-cassandra-server.txt)
![screen shot 2017-10-12 at 11 56 34 am](https://user-images.githubusercontent.com/569360/31513952-cbb25392-af44-11e7-9884-74e634f06185.png)

**Comment by robertdale** [comment] 2017-10-12 19:34
Could you try this solution on the list - https://groups.google.com/d/msg/janusgraph-users/-ugZB8oUV40/X9aQ3YSZCAAJ
Please close this issue if that works.

**Comment by AnnuSharma** [comment] 2017-10-12 20:31
Hi Robert, I checked and that line in cassandra-env.sh is already commented. Its not that I am 'always' unable to connect to cassandra. Its intermittent. More so when a new keyspace is being configured. When I explicit created the keyspace and tables in Cassandra and try to being up a janus server using that, I don't face this issue as often. Thanks!

**Comment by robertdale** [comment] 2017-10-12 20:43
From the JanusGraph side, this has nothing to do with creating keyspaces.
It's not even connecting to Cassandra.  After you get this error, have you
confirmed that Cassandra is actually up, running, listening on the thrift
(9160) port with nodetool?

Robert Dale

**Comment by AnnuSharma** [comment] 2017-10-12 21:18
Hi Robert,
So after I got that error, I deployed janus using the same keyspace and it succeeded. (Wouldn't have it thrift server was not up, I suppose?). I do think thrift is up and running. Please look at the screenshot. Thanks. 
- Annu
![screen shot 2017-10-12 at 2 18 46 pm](https://user-images.githubusercontent.com/569360/31519741-347da080-af58-11e7-869a-0c3f91072757.png)

**Comment by robertdale** [comment] 2017-10-12 21:28
Is Cassandra **always** running?  If it's started **as-needed**, then it would seem it's a timing issue. You should probably run nodetool to wait and verify that Cassandra is up and running **before** starting JanusGraph Server.  See `bin/janusgraph.sh` on how to incorporate that into a script.

**Comment by AnnuSharma** [comment] 2017-10-12 21:56
Hi,

I did verify that thrift was running using 'nodetool statusthrift'. In fact I kept it running in a loop through bash script while I was trying to redeploy janus. It always showed status as running. Interestingly, I hit a new error this time. Please look at the snapshot. 

Again, when I re-deployed the server after this it succeeded. 

![screen shot 2017-10-12 at 2 52 12 pm](https://user-images.githubusercontent.com/569360/31521168-5f74b90e-af5d-11e7-9fec-c19dd3bd48c7.png)

**Comment by robertdale** [comment] 2017-10-13 17:37
What versions of JanusGraph, Cassandra are you using?

**Comment by AnnuSharma** [comment] 2017-10-13 17:48
janusgraph-0.1.0-hadoop2 and Cassandra 3.9

**Comment by robertdale** [comment] 2017-10-13 17:59
Ok, 3.9 is not a supported Cassandra version - http://docs.janusgraph.org/0.1.0/version-compat.html
I'm closing this issue as 'not a bug'. 
You should give JanusGraph 0.2.0 a try when it's released (Real Soon Now).  Feel free to reopen this issue or create a new one if you continue to experience problems.

**Comment by AnnuSharma** [comment] 2017-10-13 23:30
Hi I downgraded to Cassandar 2.1, but I still get exceptions on deployment. PFA stacktrace, 
<img width="1440" alt="screen shot 2017-10-13 at 4 18 37 pm" src="https://user-images.githubusercontent.com/569360/31569919-df4ac2e6-b033-11e7-9bae-5a0a52dd2394.png">
<img width="617" alt="screen shot 2017-10-13 at 4 21 00 pm" src="https://user-images.githubusercontent.com/569360/31569920-e0944a8c-b033-11e7-9e0c-1a1984d4794d.png">

**Comment by sjudeng** [comment] 2017-10-16 18:25
Can you override your Docker entrypoint to ensure/wait for the C* port to be accessible before starting Gremlin Server?

**Comment by AnnuSharma** [comment] 2017-10-16 19:23
Hi @sjudeng I have been getting a bunch of different errors on janus startup. "keyspace doesn't exit", "unavailablException()", "socketReadTimeout()". In all of these cases, the keyspace gets partially initialised. Its not that Cassandra was not reachable, but somehow the whole transaction didn't happen.

**Comment by pluradj** [comment] 2017-10-17 01:11
This sounds more environmental than anything specific that JanusGraph is doing. When I've encountered issues like this, it's usually because the Cassandra node is running in a suboptimal environment -- like if storage on a SAN instead of a local SSD or if there's a big latency between the Gremlin Server and the Cassandra node. Also see the Cassandra [recommended production settings](http://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/config/configRecommendedSettings.html).

A workaround is to create the keyspace manually on the Cassandra node before connecting the Gremlin Server to it. How many Cassandra nodes are you working with? Are you setting any specific read/write consistency, RF, or other Cassandra settings in your JanusGraph properties?

Any reason you're using JanusGraph 0.1.0 rather than 0.1.1? I don't think there's anything specific in 0.1.1 that addresses your issues, but you should be on the latest on the 0.1.z stream.

**Comment by chupman** [comment] 2019-02-07 17:26
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Closed by chupman** 2019-02-07 17:26 UTC
Labels: question
