### ISSUE TITLE
Test failure with Cassandra3InputFormatIT

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#562] opened 2017-09-28 23:15 UTC
```
$ docker run --name jg-cassandra -p 9160:9160 -p 9042:9042 -e CASSANDRA_START_RPC=true -d cassandra:3.10
$ mvn clean install -pl :janusgraph-hadoop-2 -DskipHBase -DskipCassandra -DskipCassandra3=false
...
Running org.janusgraph.hadoop.Cassandra3InputFormatIT
...
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 804.834 sec <<< FAILURE! - in org.janusgraph.hadoop.Cassandra3InputFormatIT
testReadWideVertexWithManyProperties(org.janusgraph.hadoop.Cassandra3InputFormatIT)  Time elapsed: 306.026 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[0]> but was:<[44313]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.janusgraph.hadoop.AbstractInputFormatIT.testReadWideVertexWithManyProperties(AbstractInputFormatIT.java:83)
	...
```

**Comment by mbrukman** [comment] 2017-09-29 00:48
@sjudeng – should this be marked as a blocker for 0.2.0 release?

**Comment by sjudeng** [comment] 2017-09-29 01:11
@mbrukman I wouldn't want to hold up the 0.2.0 release for this (or really anything at this point).

**Comment by sjudeng** [comment] 2017-09-29 04:16
The failure is in the check [here](https://github.com/JanusGraph/janusgraph/blob/63af9fe12fe92f186d35cb62524d5df01513aed6/janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java#L83), which was added in https://github.com/JanusGraph/janusgraph/commit/63af9fe12fe92f186d35cb62524d5df01513aed6. The property values in the list are not as expected. I suspect the issue was always there but just not detected until the additional check was added. I ran a few other similar cases and noted the issue comes up even with small list sizes and the the result varies between Integer and Double data types.

<table>
<tr>
<td rowspan="2">Size</td>
<td rowspan="2">Expected</td>
<td colspan="2" align="center">Observed</td>
</tr>
<tr>
<td>dataType=Integer</td>
<td>dataType=Double</td>
</tr>
<tr>
<td>1</td>
<td>[0]</td>
<td>[0]</td>
<td/>
</tr>
<tr>
<td>2</td>
<td>[0,1]</td>
<td>[0,1]</td>
<td/>
</tr>
<tr>
<td>3</td>
<td>[0,1,2]</td>
<td>[0,1,2]</td>
<td>[0,1,2]</td>
</tr>
<tr>
<td>4</td>
<td>[0,1,2,3]</td>
<td>[4,0,1,2]</td>
<td>[3,0,1,2]</td>
</tr>
<tr>
<td>5</td>
<td>[0,1,2,3,4]</td>
<td>[1,2,3,0,4]</td>
<td>[0,4,1,2,3]</td>
</tr>
</table>

@kedarmhaswade, @twilmes Any ideas? If nothing else it would be good to have the right caveat if we'll advertise the Cassandra 3 OLAP adapter as a new feature in the upcoming 0.2.0.

**Comment by nidmgh** [comment] 2017-10-05 18:43
Guy, 

sorry that I didn't realize this problem till now.  I wasn't able to recreate the problem on my environment (not using docker). I just rerun through mvn 
`mvn clean install -Dtest=*InputFormatIT`

Per earlier comments, it may be an incompatibility issue amongst Cassandra versions? @sjudeng , would you please kindly give me a couple pointers, I'd like to dig into it? thanks

Demai

**Comment by twilmes** [comment] 2017-10-05 19:30
Thanks for the details @sjudeng, did that size 4 result really contain a 4 for the integer test or is that a typo? If the issue is just the orderings not matching, I think an end user should assume that unless they specify a sort order, a stream of multi property results will be ordered non-deterministically. If you guys are in agreement, I think we could change these asserts to just test the contents of the results and not for an exact match including order. Granted, if that other result really contained a number that shouldn't have been in the results, that's no good! If we do want to guarantee a results order that probably needs to be documented and tested more thoroughly across storage adapters. My guess is that right now it mostly returns in insert order, but that's probably more by accident than anything else. I could be wrong though.

**Comment by sjudeng** [comment] 2017-10-05 20:08
@nidmgh I don't think it's anything you added that broke this. I think the test you added just demonstrated the issue that was already there. But if you want to get into it that'd be great! You do need to start Cassandra 3 external to JanusGraph, though. The test that fails is [Cassandra3InputFormatIT](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/Cassandra3InputFormatIT.java), which is specifically designed for Cassandra 3 and doesn't run by default. Also note that the hadoop tests run through the failsafe not surefire plugin so `-Dtest=...` won't work for test selection.

@twilmes Yeah, the values are not all the same, it's not a typo. My first thought was the same as yours regarding property order ... but there's only one property. It's not multiple properties (despite the variable in the test being called `numProps`), it's the size of the list value for the single property. So since it's a single property value I'd think it would be the same (including order), though again it's not even the same excluding order.

**Comment by twilmes** [comment] 2017-10-05 20:14
Cool, yeah, I wasn't very clear, I see that it's a single multi-property. I'll be honest, I was hoping that was a typo... I'd still expect multi-property order being non-deterministic but yeah, bogus values aren't good. I'll take a look and see if I can track down the disparity too.

**Comment by sjudeng** [comment] 2017-10-05 20:27
@twilmes That makes sense. Thanks for looking at it.

**Comment by twilmes** [comment] 2017-10-05 21:16
@sjudeng out of curiosity, did you notice this test running incredibly slow even when you dropped `numProps` way down?

**Comment by sjudeng** [comment] 2017-10-05 22:00
@twilmes Yeah I do remember that, it was a bit painful (and that's why the above test matrix isn't bigger). Is it much slower than the default Cassandra 2 version?

**Comment by twilmes** [comment] 2017-10-06 19:41
It shouldn't be, and in fact if you just run manual OLAP queries from the console using the C*3 record reader against the bundled C* 2 it's fine. I need to double check, but running against a non-dockerized C* 3 previously with the updated record reader was also fine. The issue appears to be despite the data set being tiny, when we run the tests, 256 separate splits (token ranges) are being queried, vs. under 5-10 at most previously.

**Comment by sjudeng** [comment] 2017-10-07 18:27
@twilmes I think it's the `num_tokens` configuration in cassandrda.yml. It looks like it's defaulting to 256 in more recent versions of Cassandra. When I change this to 4 (to match the value used in embedded C* used in tests) it resolves the performance issue.

Also did you ever reproduce the issue with an unexpected number in the results, or just the order difference? I'm not reproducing that anymore, so I apologize maybe (hopefully) it was a typo after all. When I run the tests the values are comparing okay (disregarding order), both with num_tokens of 256 and 4.

**Comment by twilmes** [comment] 2017-10-09 13:42
Ah yes, I see that comment in the bundled `casandra.yaml` for num_tokens, that explains it. Thanks. All my tests runs were fine, minus the ordering, so I couldn't reproduce the issue. I'll check your related pr out.

**Closed** 2017-10-11 13:29 UTC
Labels: bug
