### ISSUE TITLE
Different behaviors when adding "dedup()"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [JanusGraph/janusgraph#4341] opened 2024-03-19 05:57 UTC
I execute 2 queries on my empty JanusGraph database ,and an error occurs.

JanusGraph version: 1.0.0
operating system: windows 10

first query:
g.addV().addV().project('a0').by(__.constant(1)).limit(0)

second query:
g.addV().addV().project('a0').by(__.constant(1)).dedup().limit(0)

The first query creates 1 node but the second creates 2 nodes.

And I think they should both create 2 nodes in database.

**Comment by li-boxuan** [comment] 2024-03-19 06:12
Looks like you are using some tools to capture graph database bugs. I would recommend using TinkerGraph unless you want to test some JanusGraph-specific feature. I didn't check but I think the behavior you described could be reproduced in TinkerGraph as well. In that case, please submit the bug report to apache/tinkerpop rather than janusgraph/janusgraph.

**Comment by ljhhuxiaoba** [comment] 2024-03-19 06:44
Thank you for your response. But I was wondering if there is any relationship between Janusgraph and Tinkergraph?Also, I don't know how to submit these issues on TinkerGraph, could you give me some tips?

**Comment by li-boxuan** [comment] 2024-03-19 06:51
https://issues.apache.org/jira/projects/TINKERPOP/issues

TinkerGraph is the computation framework that JanusGraph along many other databases use. Most query bugs you found, if they are indeed bugs, belong to TinkerPop codebase. TinkerGraph is the in-memory graph in TinkerPop codebase for experimental & learning purpose.

**Comment by ljhhuxiaoba** [comment] 2024-03-19 06:53
Got it. Thanks for your patience！

**Comment by ljhhuxiaoba** [comment] 2024-03-19 07:13
I just ran both queries on TinkerGraph. The first query created no nodes and the second query created 2 nodes. I'm wondering if the inconsistent behavior of the first query on TinkerGraph and JanusGraph could possibly imply a bug on JanusGraph?

**Comment by li-boxuan** [comment] 2024-03-19 08:03
> if the inconsistent behavior of the first query on TinkerGraph and JanusGraph could possibly imply a bug on JanusGraph

You could say so. JanusGraph should behave the same as TinkerGraph (most of the time), if versions are the same. JanusGraph 1.0.0 uses TinkerPop 3.7.0.

**Comment by ljhhuxiaoba** [comment] 2024-03-19 12:14
The same is true for TinkerPop 3.7.0.
And I also check other issues on TinkerPop,these gremlin queries all failed to execute and I have also submitted some to TinkerPop.
But I'm not sure which of TinkerPop or JanusGraph is acting correctly. So please, do you have time to check if these issues are bugs on JanusGraph' side?
Sincerely thanks!

**Comment by FlorianHockmann** [comment] 2024-03-27 15:14
> I just ran both queries on TinkerGraph. The first query created no nodes and the second query created 2 nodes.

Can you please show exactly which steps you took to test this with TinkerGraph? Because I also tried it and I got the same result that you got for JanusGraph: 1 created vertex for the first query and 2 vertices for the second query:

```groovy
gremlin> graph = TinkerGraph.open()
==>tinkergraph[vertices:0 edges:0]
gremlin> g = traversal().withEmbedded(graph)
==>graphtraversalsource[tinkergraph[vertices:0 edges:0], standard]
gremlin> g.V()
gremlin> g.addV().addV().project('a0').by(__.constant(1)).limit(0) // first query
gremlin> g.V()
==>v[0]
gremlin> g.V().drop() // ensure that the graph is empty again
gremlin> g.V()
gremlin> g.addV().addV().project('a0').by(__.constant(1)).dedup().limit(0) // second query
gremlin> g.V()
==>v[1]
==>v[2]
```

I executed this with the Gremlin Console Docker image, version 3.7.0:

```bash
$ docker run --rm -it docker.io/tinkerpop/gremlin-console:3.7.0
```

**Comment by ljhhuxiaoba** [comment] 2024-03-28 02:21
Sorry, I realized that I incorrectly used the previous version instead of 3.7.0. 
The situation is the same after I tried following your steps. May I ask if this is a bug in your opinion?

**Comment by FlorianHockmann** [comment] 2024-03-28 07:46
I'm not sure. I think the traversal is really weird. `project('a0').by(__.constant(1))` doesn't really do much. It just converts the traverser into a map with the key `a0` and the value `1`.
So you can get the same results also without the `project().by()`:
* first traversal: `g.addV().addV().limit(0)` -> creates 1 vertex
* second traversal: `g.addV().addV().dedup().limit(0)` -> creates 2 vertices

And `limit(0)` is also strange and I don't really know what the expected behavior should be here with Gremlin.

But this is a question that you can really better ask in one of the TinkerPop community channels like its [Discord server](https://discord.gg/tinkerpop) or [the user mailing list](https://groups.google.com/group/gremlin-users).

I'm closing this issue now as it's clear that we are not talking about a bug in JanusGraph here.

**Closed by FlorianHockmann** 2024-03-28 07:46 UTC
Labels: kind/bug/possible
