### ISSUE TITLE
Issues about reindexing on MapReduce

### ISSUE THREAD

**Issue by greatsxm** [JanusGraph/janusgraph#361] opened 2017-06-25 03:32 UTC
I use HBase as backend and I want to reindex on a graph by using mapreduce.
But I found some errors as follow:
```
gremlin> hbase_g=JanusGraphFactory.build().set("storage.backend","hbase").set("storage.hostname","192.168.1.64:2181,192.168.1.65:2181,192.168.1.66:2181").set("storage.hbase.ext.zookeeper.znode.parent","/hbase-unsecure").set("storage.hbase.table","aapi_graph").open()
11:13:52 WARN  org.janusgraph.graphdb.database.idassigner.placement.PartitionIDRange  - Individual key range is too small for partition block - result would be empty; hence ignored: KeyRange(left:  72-  0-  0-  0-  7-190-  4-  0, right: 128-  0-  0-  0- 30-171-232-  0)
11:13:52 WARN  org.janusgraph.graphdb.database.idassigner.placement.PartitionIDRange  - Individual key range is too small for partition block - result would be empty; hence ignored: KeyRange(left:  72-  0-  0-  0-  7-190-  4-  0, right: 128-  0-  0-  0- 30-171-232-  0)
==>standardjanusgraph[hbase:[192.168.1.64:2181, 192.168.1.65:2181, 192.168.1.66:2181]]
gremlin> mgmt = hbase_g.openManagement();
==>org.janusgraph.graphdb.database.management.ManagementSystem@506aabf6
gremlin> mr = new MapReduceIndexManagement(hbase_g);
==>org.janusgraph.hadoop.MapReduceIndexManagement@2f382a5e
gremlin> mr.updateIndex(mgmt.getGraphIndex("byVIDComposite"), SchemaAction.REINDEX).get();
11:14:43 WARN  org.apache.hadoop.mapreduce.JobResourceUploader  - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
11:14:48 WARN  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper  - Unable to create ZooKeeper Connection
java.net.UnknownHostException: [192.168.1.64: invalid IPv6 address
        at java.net.InetAddress.getAllByName(InetAddress.java:1146)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
```

I reduce the number of hosts and still some errors have occurred as below:
```
gremlin> hbase_g=JanusGraphFactory.build().set("storage.backend","hbase").set("storage.hostname","192.168.1.64:2181").set("storage.hbase.ext.zookeeper.znode.parent","/hbase-unsecure").set("storage.hbase.table","aapi_graph").open()
11:13:52 WARN  org.janusgraph.graphdb.database.idassigner.placement.PartitionIDRange  - Individual key range is too small for partition block - result would be empty; hence ignored: KeyRange(left:  72-  0-  0-  0-  7-190-  4-  0, right: 128-  0-  0-  0- 30-171-232-  0)
11:13:52 WARN  org.janusgraph.graphdb.database.idassigner.placement.PartitionIDRange  - Individual key range is too small for partition block - result would be empty; hence ignored: KeyRange(left:  72-  0-  0-  0-  7-190-  4-  0, right: 128-  0-  0-  0- 30-171-232-  0)
==>standardjanusgraph[hbase:[192.168.1.64]]
gremlin> mgmt = hbase_g.openManagement();
==>org.janusgraph.graphdb.database.management.ManagementSystem@56e9a474
gremlin> mr = new MapReduceIndexManagement(hbase_g);
==>org.janusgraph.hadoop.MapReduceIndexManagement@1682c08c
gremlin> mr.updateIndex(mgmt.getGraphIndex("byVIDComposite"), SchemaAction.REINDEX).get();
10:06:24 WARN  org.apache.hadoop.mapreduce.JobResourceUploader  - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.util.concurrent.ExecutionException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Can't get the locations
        at org.janusgraph.hadoop.MapReduceIndexManagement$FailedJobFuture.get(MapReduceIndexManagement.java:297)
        at org.janusgraph.hadoop.MapReduceIndexManagement$FailedJobFuture.get(MapReduceIndexManagement.java:267)
        at java_util_concurrent_Future$get.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
```

**Comment by therealnb** [comment] 2017-07-27 13:39
I don't know of anyone who has made this work (see https://groups.google.com/forum/#!topic/janusgraph-users/aM9YThbqU-4 ). I would like to know if they have. 

Mind you, my errors are different to yours.

**Comment by ezhong0812** [comment] 2017-08-03 05:57
I use Cassandra as backend and I reindex using mapreduce.
But I found some errors about ClassNotFoundException:
`gremlin> mr.updateIndex(mgmt.getGraphIndex(index_name), SchemaAction.REINDEX).get()
Error: java.lang.ClassNotFoundException: org.janusgraph.diskstorage.configuration.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	at org.apache.hadoop.mapreduce.task.JobContextImpl.getMapperClass(JobContextImpl.java:186)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:745)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

Error: java.lang.ClassNotFoundException: org.janusgraph.diskstorage.configuration.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	at org.apache.hadoop.mapreduce.task.JobContextImpl.getMapperClass(JobContextImpl.java:186)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:745)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143

Error: java.lang.ClassNotFoundException: org.janusgraph.diskstorage.configuration.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	at org.apache.hadoop.mapreduce.task.JobContextImpl.getMapperClass(JobContextImpl.java:186)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:745)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143

Error: java.lang.ClassNotFoundException: org.janusgraph.diskstorage.configuration.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
	at org.apache.hadoop.mapreduce.task.JobContextImpl.getMapperClass(JobContextImpl.java:186)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:745)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)`

the graph config as below:
`
space = "jason3"
config = JanusGraphFactory.build()

config.set("storage.cassandra.keyspace", space)

config.set("storage.backend", "cassandrathrift")
config.set("storage.hostname", "127.0.0.1")
config.set("storage.port", 9160)
config.set("storage.read-time", 100000)

config.set("storage.cassandra.atomic-batch-mutate", false)
config.set("storage.cassandra.compression", false)


config.set("index.search.backend", "elasticsearch")
config.set("index.search.hostname", "127.0.0.1")
config.set("index.search.port", 9300)
config.set("index.search.index-name", space)

config.set("index.search.elasticsearch.client-only", true)
graph = config.open()
g = graph.traversal()
`

**Comment by ezhong0812** [comment] 2017-08-04 10:58
I copy all  *.jar from janusgraph0.1.1/lib/ to hadoop2.7.3/share/hadoop/mapreduce/lib ,solve the error of ClassNotFoundException ,
and I got a new error :
```
Error: java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.es.ElasticSearchIndex
        at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:69)
        at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
        at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:464)
        at org.janusgraph.diskstorage.Backend.<init>(Backend.java:149)
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1850)
        at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:134)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:97)
        at org.janusgraph.hadoop.scan.HadoopVertexScanMapper.setup(HadoopVertexScanMapper.java:37)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:143)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
        ... 16 more
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:279)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:198)
        at org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient.execute(InternalTransportClusterAdminClient.java:86)
        at org.elasticsearch.client.support.AbstractClusterAdminClient.health(AbstractClusterAdminClient.java:127)
        at org.elasticsearch.action.admin.cluster.health.ClusterHealthRequestBuilder.doExecute(ClusterHealthRequestBuilder.java:92)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
        at org.janusgraph.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:215)
        ... 21 more

Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143
```
and it works reindex use JanusGraphManagement .

**Comment by ezhong0812** [comment] 2017-08-07 10:24
```
Error: java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.es.ElasticSearchIndex
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
```
caused by es search backend config
`config.set("index.search.hostname", "a.b.c.d,a1,b1,c1,d1")`

and 
`config.set("index.search.hostname", "a.b.c.d")`
is ok.

but ,if you do not use MapReduceIndexManagement , both config is ok.

--------

when i use pseudo cluster on  single machine, i get the exception http://docs.janusgraph.org/0.1.1/index-admin.html , 29.3.3. Cassandra Mappers Fail with "Too many open files"

**Comment by ezhong0812** [comment] 2017-08-10 07:47
and ,I got new exception:
```
Error: java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Frame size (93834405) larger than max length (15728640)!
Caused by: org.apache.thrift.transport.TTransportException: Frame size (93834405) larger than max length (15728640)!
```
the configuration `storage.cassandra.frame-size-mb` does not work。

so I  modify the source code of janusgaph-hadoop 
org.janusgraph.hadoop.formats.cassandra.CassandraBinaryInputFormat.setConf(..)
```
    public void setConf(final Configuration config) {
        super.setConf(config);

        // Copy some JanusGraph configuration keys to the Hadoop Configuration keys used by Cassandra's ColumnFamilyInputFormat
        ConfigHelper.setInputInitialAddress(config, janusgraphConf.get(GraphDatabaseConfiguration.STORAGE_HOSTS)[0]);
        if (janusgraphConf.has(GraphDatabaseConfiguration.STORAGE_PORT))
            ConfigHelper.setInputRpcPort(config, String.valueOf(janusgraphConf.get(GraphDatabaseConfiguration.STORAGE_PORT)));
        if (janusgraphConf.has(GraphDatabaseConfiguration.AUTH_USERNAME))
            ConfigHelper.setInputKeyspaceUserName(config, janusgraphConf.get(GraphDatabaseConfiguration.AUTH_USERNAME));
        if (janusgraphConf.has(GraphDatabaseConfiguration.AUTH_PASSWORD))
            ConfigHelper.setInputKeyspacePassword(config, janusgraphConf.get(GraphDatabaseConfiguration.AUTH_PASSWORD));

        // Copy keyspace, force the CF setting to edgestore, honor widerows when set
        final boolean wideRows = config.getBoolean(INPUT_WIDEROWS_CONFIG, false);
        // Use the setInputColumnFamily overload that includes a widerows argument; using the overload without this argument forces it false
        ConfigHelper.setInputColumnFamily(config, janusgraphConf.get(AbstractCassandraStoreManager.CASSANDRA_KEYSPACE),
                mrConf.get(JanusGraphHadoopConfiguration.COLUMN_FAMILY_NAME), wideRows);
        log.info("Set keyspace: {}", janusgraphConf.get(AbstractCassandraStoreManager.CASSANDRA_KEYSPACE));

        if (janusgraphConf.has(AbstractCassandraStoreManager.THRIFT_FRAME_SIZE_MB)) {
            ConfigHelper.setThriftFramedTransportSizeInMb(config, janusgraphConf.get(AbstractCassandraStoreManager.THRIFT_FRAME_SIZE_MB));
        } 

        // Set the column slice bounds via Faunus's vertex query filter
        final SlicePredicate predicate = new SlicePredicate();
        //final int rangeBatchSize = config.getInt(RANGE_BATCH_SIZE_CONFIG, Integer.MAX_VALUE);
        final int rangeBatchSize = ConfigHelper.getRangeBatchSize(config);
       predicate.setSlice_range(getSliceRange(JanusGraphHadoopSetupCommon.DEFAULT_SLICE_QUERY, rangeBatchSize)); // TODO stop slicing the whole row
        ConfigHelper.setInputSlicePredicate(config, predicate);
    }
```

I set the AbstractCassandraStoreManager.THRIFT_FRAME_SIZE_MB and change the rangeBatchSize .

replace the janusgraph-hadoop-0.1.1.jar after build ，
and modify the graph configuration
`config.set("storage.cassandra.frame-size-mb",128)`
the code 
`mr.updateIndex(mgmt.getGraphIndex(index_name), SchemaAction.REINDEX).get() `
works.

**Comment by ezhong0812** [comment] 2017-08-10 08:05
Unfortunately，the test graph has 2 vertices,1000000 edges, after reindex on edge , elasticsearch only has 4094 docs...

**Comment by ezhong0812** [comment] 2017-08-10 10:59
I make the mistake
` final int rangeBatchSize = ConfigHelper.getRangeBatchSize(config);`
Revert to the original
`final int rangeBatchSize = config.getInt(RANGE_BATCH_SIZE_CONFIG, Integer.MAX_VALUE);`

1000000 edges,after reindex on edge , elasticsearch show 100000 docs... ,but  can query all edge in gremlin console use g.E().has('attr', textContainsRegex('str'))

**Comment by ezhong0812** [comment] 2017-08-22 02:54
I did some tests , reindex index on edge by MapReduceIndexManagement ，can only reindex 100000 edge of the same vertex at most.

I tracked source code and found the limit was set by org.janusgraph.graphdb.olap.QueryContainer.java
the private method Query relations(RelationCategory returnType) of inner class QueryBuilder

`    slices.add(sq.updateLimit(bq.isFitted() ? vq.getLimit() : hardQueryLimit));`

the hardQueryLimit was 
`public static final int DEFAULT_HARD_QUERY_LIMIT = 100000;`

Is there anyone who can provide some information about this limit ?

**Comment by apurva16shiva** [comment] 2018-01-30 03:41
hi greatsxm,
how you solve your problem.
I am also using HBase as backend and I want to reindex on a graph by using mapreduce. I am also getting same error. Please guid me

**Comment by genganpeng** [comment] 2018-07-11 08:51
modify address list of storage.hostname , only one zk
 address is ok！eg storage.hostname=192.168.1.64:2181

**Comment by chupman** [comment] 2019-02-07 17:24
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Closed by chupman** 2019-02-07 17:24 UTC
Labels: question
