### ISSUE TITLE
Composite index inconsistent

### ISSUE THREAD

**Issue by mbbeaubi** [JanusGraph/janusgraph#1448] opened 2019-02-26 16:56 UTC
Hi,

I have two composite indices on a vertex. I have encountered a situation where index A contains the vertex but index B does not. I'm not sure how this came about but it is my understanding that this type of thing can happen with an hbase backend.

Would running the transaction recovery process in the background fix these types of errors or is that only for mixed indices?

What's the recommendation for this situation?

Thanks!

**Comment by fufler** [comment] 2019-05-06 05:47
@mbbeaubi Do you still experience the same behaviour? If yes, could you please provide a reproducer?

**Comment by mbbeaubi** [comment] 2019-06-18 17:21
I don't have any reproduction steps. I think the issue was caused by a corrupted backup. Just wondering if anyone has put any work into a utility to rebuild janus indices? I know there is mention in the documentation of doing this.

**Comment by FlorianHockmann** [comment] 2019-06-19 07:05
Closing this as it's not a bug report any more. [Reindexing](https://docs.janusgraph.org/0.3.1/index-admin.html) should do what you want. If not, please ask on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users).

**Closed by FlorianHockmann** 2019-06-19 07:05 UTC
Labels: kind/bug/possible
