### ISSUE TITLE
Fix errors in docbook to html conversion

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#231] opened 2017-04-25 19:08 UTC
`mvn install -DskipTests=true`
[INFO] --- xml-maven-plugin:1.0:transform (docbook-to-htmlsingle) @ janusgraph-dist ---
[INFO] Transforming file: /Users/amcp/git/janusgraph/janusgraph-dist/target/docs/docbook/index.xml
ERROR: xref linking to es-cfg-common-opts has no generated link text.
Error: no ID for constraint linkend: es-cfg-common-opts.

**Comment by amcp** [comment] 2017-04-25 19:09
also
[INFO] --- xml-maven-plugin:1.0:transform (docbook-to-htmlchunk) @ janusgraph-doc ---
[INFO] Transforming file: /Users/amcp/git/janusgraph/janusgraph-doc/target/docs/docbook/index.xml
...
Writing /Users/amcp/git/janusgraph/janusgraph-doc/target/docs/chunk/direct-index-query.html for chapter(direct-index-query)
ERROR: xref linking to es-cfg-common-opts has no generated link text.
Error: no ID for constraint linkend: es-cfg-common-opts.

**Comment by robertdale** [comment] 2017-11-30 03:49
@amcp I'm unable to reproduce this on the latest 0.2 and master branches.  Can we close this?

**Comment by chupman** [comment] 2019-02-07 17:42
This bug has been resolved on the 0.2 branch.

**Closed by chupman** 2019-02-07 17:42 UTC
Labels: cleanup, docs
